import type { ReactNode } from "react";
import type { MoneyString } from "../money";
import { DescriptionList, Money, StatusBadge, Timeline, type TimelineItem } from "./data-display";
import type { Intent } from "./primitives";

type CardBaseProps = { title: ReactNode; subtitle?: ReactNode; status?: { label: ReactNode; intent?: Intent }; actions?: ReactNode; children?: ReactNode; className?: string };
function OperationalCard({ title, subtitle, status, actions, children, className = "" }: CardBaseProps) { return <article className={`kolbe-operational-card ${className}`.trim()}><header><div><h3>{title}</h3>{subtitle ? <p>{subtitle}</p> : null}</div>{status ? <StatusBadge intent={status.intent}>{status.label}</StatusBadge> : null}</header>{children}{actions ? <footer>{actions}</footer> : null}</article>; }

export function AddressCard(props: CardBaseProps & { lines: readonly string[]; postalCode?: string }) { return <OperationalCard {...props}><address>{props.lines.map((line) => <span key={line}>{line}</span>)}{props.postalCode ? <bdi className="kolbe-ltr kolbe-numeric" dir="ltr">{props.postalCode}</bdi> : null}</address></OperationalCard>; }
export function OrderCard(props: CardBaseProps & { orderCode: string; total: MoneyString; placedAt?: ReactNode; timeline?: readonly TimelineItem[] }) { return <OperationalCard {...props}><DescriptionList items={[{ term: "کد سفارش", detail: props.orderCode, ltr: true }, { term: "مبلغ", detail: <Money value={props.total} /> }, ...(props.placedAt ? [{ term: "ثبت", detail: props.placedAt }] : [])]} />{props.timeline ? <Timeline items={props.timeline} /> : null}</OperationalCard>; }
export function InvoiceCard(props: CardBaseProps & { invoiceCode: string; amount: MoneyString; dueAt?: ReactNode }) { return <OperationalCard {...props}><DescriptionList items={[{ term: "شماره فاکتور", detail: props.invoiceCode, ltr: true }, { term: "مبلغ", detail: <Money value={props.amount} /> }, ...(props.dueAt ? [{ term: "سررسید", detail: props.dueAt }] : [])]} /></OperationalCard>; }
export function MembershipCard(props: CardBaseProps & { plan: ReactNode; validUntil?: ReactNode; benefits?: readonly ReactNode[] }) { return <OperationalCard {...props}><DescriptionList items={[{ term: "طرح", detail: props.plan }, ...(props.validUntil ? [{ term: "اعتبار تا", detail: props.validUntil }] : [])]} />{props.benefits ? <ul>{props.benefits.map((benefit, index) => <li key={index}>{benefit}</li>)}</ul> : null}</OperationalCard>; }
export function SupportCaseCard(props: CardBaseProps & { caseCode: string; updatedAt?: ReactNode; summary?: ReactNode }) { return <OperationalCard {...props}><DescriptionList items={[{ term: "شماره پرونده", detail: props.caseCode, ltr: true }, ...(props.updatedAt ? [{ term: "آخرین به‌روزرسانی", detail: props.updatedAt }] : [])]} />{props.summary ? <p>{props.summary}</p> : null}</OperationalCard>; }
