import { useMemo, useState, type FormEvent } from "react";
import { MapPin, Plus } from "lucide-react";
import { AddressCard, Button, Dialog, EmptyState, InlineNotice, TextField } from "../../shared/components";
import { canonicalClient } from "../../shared/http/clients";
import { buyerApi, type AddressInput, type BuyerAddress } from "../../shared/vip/buyer";
import { RemoteBoundary, useRemote, VipRoutePage } from "./VipPageParts";

const blank: AddressInput = { label: "", recipientName: "", recipientPhone: "", province: "", city: "", addressLine: "", plaque: "", unit: "", postalCode: "", isDefault: false };

export function VipAddressesPage() {
  const api = useMemo(() => buyerApi(canonicalClient()), []); const remote = useRemote(() => api.addresses(), [api]);
  const [editing, setEditing] = useState<BuyerAddress | "new" | null>(null); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState("");
  const mutate = async (id: string, action: () => Promise<unknown>) => { setBusyId(id); setError(""); try { await action(); remote.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "عملیات آدرس ممکن نشد"); } finally { setBusyId(null); } };
  return <VipRoutePage eyebrow="SHIPPING" title="آدرس‌های ارسال" description="مقصدهای ذخیره‌شدهٔ حساب؛ مالکیت همهٔ عملیات از نشست تعیین می‌شود.">
    <div className="vip-page-actions"><Button onClick={() => setEditing("new")}><Plus aria-hidden="true" /> افزودن آدرس</Button></div>{error ? <InlineNotice intent="danger">{error}</InlineNotice> : null}
    <RemoteBoundary state={remote}>{({ addresses }) => addresses.length ? <div className="vip-card-grid">{addresses.map((address) => <AddressCard key={address.id} title={address.label} subtitle={address.recipientName} status={address.isDefault ? { label: "پیش‌فرض", intent: "success" } : undefined} lines={[`${address.province}، ${address.city}`, address.addressLine, `پلاک ${address.plaque || "—"}${address.unit ? `، واحد ${address.unit}` : ""}`]} postalCode={address.postalCode} actions={<div className="vip-inline-actions"><Button variant="secondary" onClick={() => setEditing(address)}>ویرایش</Button>{!address.isDefault ? <Button variant="quiet" disabled={busyId === address.id} onClick={() => void mutate(address.id, () => api.defaultAddress(address.id))}>پیش‌فرض</Button> : null}<Button variant="danger" disabled={busyId === address.id} onClick={() => { if (confirm("این آدرس حذف شود؟")) void mutate(address.id, () => api.deleteAddress(address.id)); }}>حذف</Button></div>} />)}</div> : <EmptyState title="آدرسی ثبت نشده است" description="برای آماده‌سازی سفارش، نخست یک نشانی تحویل معتبر اضافه کنید." action={<Button onClick={() => setEditing("new")}><MapPin aria-hidden="true" /> ثبت نخستین آدرس</Button>} />}</RemoteBoundary>
    {editing ? <AddressDialog address={editing === "new" ? undefined : editing} api={api} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); remote.reload(); }} /> : null}
  </VipRoutePage>;
}

function AddressDialog({ address, api, onClose, onSaved }: { address?: BuyerAddress; api: ReturnType<typeof buyerApi>; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<AddressInput>(address ? { label: address.label, recipientName: address.recipientName, recipientPhone: address.recipientPhone, province: address.province, city: address.city, addressLine: address.addressLine, plaque: address.plaque || "", unit: address.unit || "", postalCode: address.postalCode, isDefault: address.isDefault } : blank);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const field = (name: keyof AddressInput) => ({ value: String(form[name] ?? ""), onChange: (e: React.ChangeEvent<HTMLInputElement>) => setForm((v) => ({ ...v, [name]: e.target.value })) });
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { address ? await api.updateAddress(address.id, form, address.version) : await api.createAddress(form); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "ذخیره آدرس ممکن نشد"); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }} title={address ? "ویرایش آدرس" : "آدرس تازه"} description="کدپستی ده‌رقمی و شماره موبایل معتبر وارد کنید."><form className="vip-form-grid" onSubmit={(e) => void submit(e)}><TextField label="عنوان" {...field("label")} required /><TextField label="نام تحویل‌گیرنده" {...field("recipientName")} required /><TextField label="موبایل" dir="ltr" inputMode="tel" {...field("recipientPhone")} required /><TextField label="استان" {...field("province")} required /><TextField label="شهر" {...field("city")} required /><TextField label="نشانی" className="vip-form-span" {...field("addressLine")} required /><TextField label="پلاک" {...field("plaque")} /><TextField label="واحد" {...field("unit")} /><TextField label="کدپستی" dir="ltr" inputMode="numeric" pattern="[0-9۰-۹]{10}" {...field("postalCode")} required /><label className="vip-check"><input type="checkbox" checked={form.isDefault} onChange={(e) => setForm((v) => ({ ...v, isDefault: e.target.checked }))} /> آدرس پیش‌فرض</label>{error ? <InlineNotice intent="danger" className="vip-form-span">{error}</InlineNotice> : null}<div className="vip-form-actions vip-form-span"><Button variant="quiet" onClick={onClose}>انصراف</Button><Button type="submit" disabled={busy}>{busy ? "در حال ذخیره" : "ذخیره آدرس"}</Button></div></form></Dialog>;
}
