import { useMemo, useRef, useState } from "react";
import { Button, Dialog, EmptyState, InlineNotice, Money, SelectField, StatusBadge, Surface, TextField } from "../../shared/components";
import { canonicalClient } from "../../shared/http/clients";
import { buyerApi, type BuyerRequest } from "../../shared/vip/buyer";
import { faDate, RemoteBoundary, statusLabel, useRemote, VipRoutePage } from "./VipPageParts";

export function VipRequestsPage() {
  const api = useMemo(() => buyerApi(canonicalClient()), []); const remote = useRemote(() => api.requests(), [api]); const [active, setActive] = useState<BuyerRequest | null>(null); const [ordering, setOrdering] = useState<BuyerRequest | null>(null); const [reviewing, setReviewing] = useState<BuyerRequest | null>(null); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const idem = useRef(crypto.randomUUID());
  const cancel = async () => { if (!active) return; setBusy(true); setError(""); try { await api.cancelRequest(active.id, reason.trim(), active.version, idem.current); setActive(null); setReason(""); idem.current = crypto.randomUUID(); remote.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "لغو درخواست ممکن نشد"); } finally { setBusy(false); } };
  return <VipRoutePage eyebrow="REQUESTS / RFQ" title="درخواست‌های عمده" description="درخواست‌ها، نسخهٔ پذیرفته‌شده و وضعیت مذاکره از قرارداد canonical خوانده می‌شوند."><RemoteBoundary state={remote}>{({ requests }) => requests.length ? <div className="vip-record-list">{requests.map((request) => <Surface key={request.id} className="vip-request-row"><div><strong>درخواست {request.id}</strong><small>{faDate(request.createdAt)} · {request.quantity} واحد</small></div><StatusBadge>{statusLabel(request.status)}</StatusBadge><bdi dir="ltr">v{request.version}</bdi>{request.rejectionReason ? <p>{request.rejectionReason}</p> : null}<div className="vip-inline-actions">{request.status === "revision_requested" ? <Button onClick={() => setReviewing(request)}>بررسی پیشنهاد فروشنده</Button> : null}{request.status === "accepted" ? <Button onClick={() => { setOrdering(request); idem.current = crypto.randomUUID(); }}>تبدیل به سفارش</Button> : null}{["pending", "revision_requested", "accepted"].includes(request.status) ? <Button variant="danger" onClick={() => { setActive(request); setError(""); idem.current = crypto.randomUUID(); }}>لغو درخواست</Button> : null}</div></Surface>)}</div> : <EmptyState title="درخواستی ثبت نشده است" description="درخواست قیمت و مقدار از صفحهٔ محصول عمده و بر پایهٔ پیشنهاد واقعی فروشنده آغاز می‌شود." />}</RemoteBoundary>{active ? <Surface className="vip-cancel-panel"><h2>لغو {active.id}</h2><TextField label="دلیل لغو" value={reason} onChange={(e) => setReason(e.target.value)} required />{error ? <InlineNotice intent="danger">{error}</InlineNotice> : null}<div className="vip-inline-actions"><Button variant="quiet" onClick={() => setActive(null)}>انصراف</Button><Button variant="danger" disabled={busy || !reason.trim()} onClick={() => void cancel()}>{busy ? "در حال ثبت" : "تأیید لغو"}</Button></div></Surface> : null}{reviewing ? <ReviewRevision request={reviewing} api={api} onClose={() => setReviewing(null)} onChanged={() => { setReviewing(null); remote.reload(); }} /> : null}{ordering ? <CreateOrder request={ordering} api={api} idempotencyKey={idem.current} onClose={() => setOrdering(null)} /> : null}</VipRoutePage>;
}

function ReviewRevision({ request, api, onClose, onChanged }: { request: BuyerRequest; api: ReturnType<typeof buyerApi>; onClose: () => void; onChanged: () => void }) {
  const remote = useRemote(() => api.requestRevisions(request.id), [api, request.id]); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const idem = useRef(crypto.randomUUID());
  const respond = async (accept: boolean, revisionId: string) => { setBusy(true); setError(""); try { accept ? await api.acceptRevision(request, revisionId, idem.current) : await api.rejectRevision(request, revisionId, reason.trim(), idem.current); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : "ثبت پاسخ ممکن نشد"); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={(next) => { if (!next) onClose(); }} title="پیشنهاد بازبینی فروشنده" description="پاسخ با نسخهٔ فعلی درخواست و کلید idempotency ثبت می‌شود."><RemoteBoundary state={remote}>{({ revisions }) => { const revision = revisions.at(-1); return revision ? <div className="vip-detail-stack"><dl className="vip-revision"><div><dt>دلیل</dt><dd>{revision.reason || "—"}</dd></div><div><dt>تعداد پیشنهادی</dt><dd>{revision.proposedQuantity ?? "بدون تغییر"}</dd></div><div><dt>قیمت پیشنهادی</dt><dd>{revision.proposedUnitPrice ? <Money value={revision.proposedUnitPrice} options={{ suffix: ` ${revision.currency || "IRR"}` }} /> : "بدون تغییر"}</dd></div><div><dt>زمان پیشنهاد</dt><dd>{faDate(revision.createdAt)}</dd></div></dl><TextField label="دلیل رد (در صورت رد)" value={reason} onChange={(e) => setReason(e.target.value)} />{error ? <InlineNotice intent="danger">{error}</InlineNotice> : null}<div className="vip-inline-actions"><Button variant="danger" disabled={busy || !reason.trim()} onClick={() => void respond(false, revision.id)}>رد پیشنهاد</Button><Button disabled={busy} onClick={() => void respond(true, revision.id)}>پذیرش پیشنهاد</Button></div></div> : <EmptyState title="بازبینی‌ای ثبت نشده است" />; }}</RemoteBoundary></Dialog>;
}

function CreateOrder({ request, api, idempotencyKey, onClose }: { request: BuyerRequest; api: ReturnType<typeof buyerApi>; idempotencyKey: string; onClose: () => void }) {
  const addresses = useRemote(() => api.addresses(), [api]); const [addressId, setAddressId] = useState(""); const [payment, setPayment] = useState("transfer"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState("");
  const submit = async () => { const address = addresses.data?.addresses.find((item) => item.id === addressId) ?? addresses.data?.addresses.find((item) => item.isDefault); if (!address) { setError("یک آدرس ارسال انتخاب کنید."); return; } setBusy(true); setError(""); try { const result = await api.createOrder(request, address, payment, idempotencyKey); setCreated(result.order.orderCode); } catch (cause) { setError(cause instanceof Error ? cause.message : "ثبت سفارش ممکن نشد"); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={(next) => { if (!next) onClose(); }} title="ثبت سفارش عمده" description={`بر پایهٔ درخواست پذیرفته‌شده ${request.id}`}>{created ? <InlineNotice intent="success" title="سفارش ثبت شد">کد سفارش: {created}</InlineNotice> : <RemoteBoundary state={addresses}>{(data) => data.addresses.length ? <div className="vip-detail-stack"><SelectField label="آدرس ارسال" value={addressId || data.addresses.find((item) => item.isDefault)?.id || data.addresses[0].id} onChange={(e) => setAddressId(e.target.value)}>{data.addresses.map((address) => <option key={address.id} value={address.id}>{address.label} — {address.city}</option>)}</SelectField><SelectField label="روش پرداخت" value={payment} onChange={(e) => setPayment(e.target.value)}><option value="transfer">انتقال بانکی</option><option value="prepaid">پیش‌پرداخت</option><option value="credit">اعتباری</option><option value="on_delivery">پرداخت در تحویل</option></SelectField>{error ? <InlineNotice intent="danger">{error}</InlineNotice> : null}<Button disabled={busy} onClick={() => void submit()}>{busy ? "در حال ثبت" : "ثبت نهایی سفارش"}</Button></div> : <EmptyState title="برای ثبت سفارش آدرس لازم است" description="از بخش آدرس‌های ارسال، یک نشانی معتبر اضافه کنید." />}</RemoteBoundary>}</Dialog>;
}
