import { useState } from "react";
import Admin from "./Admin";
import Icon from "../components/Icon";
import { loadTickets, saveTickets, type SupportTicket } from "../wholesaleSupport";
import { loadWholesaleMembership } from "../wholesaleMembership";
import { fa } from "../utils/format";

const ADMIN_USER = "kolbe.admin";
const ADMIN_PASS = "KvAdmin#1405";

export default function AdminPortal() {
  const [authenticated, setAuthenticated] = useState(() => sessionStorage.getItem("kv_admin_auth") === "1");
  const [section, setSection] = useState<"retail" | "wholesale">("retail");
  const [credentials, setCredentials] = useState({ username: "", password: "" });
  const [error, setError] = useState("");

  if (!authenticated) return <main className="flex min-h-screen items-center justify-center bg-[#eef0f2] px-4"><form onSubmit={(e) => { e.preventDefault(); if (credentials.username === ADMIN_USER && credentials.password === ADMIN_PASS) { sessionStorage.setItem("kv_admin_auth", "1"); setAuthenticated(true); } else setError("نام کاربری یا رمز عبور درست نیست."); }} className="w-full max-w-sm bg-white p-7"><p className="text-[9px] tracking-[0.25em] text-neutral-400">KOLBE CONTROL ROOM</p><h1 className="mt-2 text-[22px] font-medium">ورود مدیریت</h1><p className="mt-2 text-[10.5px] leading-[1.8] text-neutral-500">ورود مستقل مدیریت فروشگاه و بخش عمده‌فروشی.</p><label className="mt-6 block text-[10px] text-neutral-500">نام کاربری<input autoFocus name="admin-username" autoComplete="username" value={credentials.username} onChange={(e) => setCredentials((value) => ({ ...value, username: e.target.value }))} className="mt-1.5 h-10 w-full border border-neutral-300 px-3 text-[12px] outline-none focus-visible:ring-2 focus-visible:ring-[#011c3a]" /></label><label className="mt-3 block text-[10px] text-neutral-500">رمز عبور<input name="admin-password" type="password" autoComplete="current-password" value={credentials.password} onChange={(e) => setCredentials((value) => ({ ...value, password: e.target.value }))} className="mt-1.5 h-10 w-full border border-neutral-300 px-3 text-[12px] outline-none focus-visible:ring-2 focus-visible:ring-[#011c3a]" /></label>{error && <p role="alert" className="mt-3 text-[10.5px] text-red-700">{error}</p>}<button type="submit" className="mt-5 h-11 w-full bg-[#011c3a] text-[12px] font-medium text-white">ورود به پنل مدیریت</button></form></main>;

  return <div className="min-h-screen bg-[#f5f5f3]"><div className="sticky top-0 z-50 flex items-center justify-between border-b border-neutral-200 bg-white px-4 py-3"><div className="flex gap-1"><button onClick={() => setSection("retail")} className={(section === "retail" ? "bg-[#011c3a] text-white" : "bg-neutral-100") + " px-4 py-2 text-[11px]"}>کلبه وینتیج</button><button onClick={() => setSection("wholesale")} className={(section === "wholesale" ? "bg-[#011c3a] text-white" : "bg-neutral-100") + " px-4 py-2 text-[11px]"}>مدیریت عمده‌فروشی</button></div><button onClick={() => { sessionStorage.removeItem("kv_admin_auth"); setAuthenticated(false); }} className="text-[10.5px] text-neutral-500 underline">خروج امن</button></div>{section === "retail" ? <Admin /> : <WholesaleAdmin />}</div>;
}

function WholesaleAdmin() {
  const [tickets, setTickets] = useState(loadTickets);
  const membership = loadWholesaleMembership();
  const orders = (() => { try { return JSON.parse(localStorage.getItem("kv_wholesale_orders") ?? "[]") as Array<{ code: string; totalQty: number; status: string; date: string }>; } catch { return []; } })();
  const updateTicket = (id: string, status: SupportTicket["status"]) => { const next = tickets.map((ticket) => ticket.id === id ? { ...ticket, status } : ticket); setTickets(next); saveTickets(next); };
  return <main className="p-4 lg:p-7"><div><p className="text-[9px] tracking-[0.2em] text-neutral-400">WHOLESALE MANAGEMENT</p><h1 className="mt-2 text-[22px] font-medium">مدیریت سرویس عمده‌فروشی</h1></div><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[membership ? "۱" : "۰", "عضو VIP فعال"], [fa(orders.length), "سفارش عمده"], [fa(orders.reduce((sum, order) => sum + order.totalQty, 0)), "واحد سفارش‌شده"], [fa(tickets.filter((ticket) => ticket.status === "باز").length), "تیکت باز"]].map(([value, label]) => <div key={label} className="border-t-2 border-[#011c3a] bg-white p-4"><p className="text-[20px] font-medium num-fa">{value}</p><p className="mt-2 text-[10px] text-neutral-500">{label}</p></div>)}</section><section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><div className="bg-white p-5"><h2 className="text-[14px] font-medium">تیکت‌های پشتیبانی</h2><div className="mt-4 divide-y divide-neutral-200">{tickets.map((ticket) => <article key={ticket.id} className="py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11.5px] font-medium">{ticket.subject}</p><p className="mt-1 text-[9.5px] text-neutral-400">{ticket.id} · {ticket.category} · {ticket.createdAt}</p></div><span className="bg-neutral-100 px-2 py-1 text-[9px]">{ticket.status}</span></div><p className="mt-2 text-[10.5px] leading-[1.8] text-neutral-600">{ticket.message}</p><div className="mt-3 flex gap-2"><button onClick={() => updateTicket(ticket.id, "پاسخ داده شده")} className="border border-[#011c3a] px-3 py-1.5 text-[9.5px]">ثبت پاسخ</button><button onClick={() => updateTicket(ticket.id, "بسته")} className="text-[9.5px] text-neutral-500 underline">بستن</button></div></article>)}{!tickets.length && <p className="py-10 text-center text-[10.5px] text-neutral-400">تیکتی ثبت نشده است.</p>}</div></div><div className="bg-white p-5"><h2 className="text-[14px] font-medium">آخرین سفارش‌های عمده</h2><div className="mt-4 divide-y divide-neutral-200">{orders.map((order) => <div key={order.code} className="flex items-center justify-between py-3 text-[10.5px]"><div><p className="font-medium num-fa">{order.code}</p><p className="mt-1 text-neutral-400">{order.date}</p></div><span>{order.status}</span><span className="num-fa">{fa(order.totalQty)} عدد</span></div>)}{!orders.length && <p className="py-10 text-center text-[10.5px] text-neutral-400">سفارشی ثبت نشده است.</p>}</div></div></section></main>;
}
