import { useMemo, useState } from "react";
import Icon from "../components/Icon";
import { fa, toman } from "../utils/format";

type Stage = "سرنخ" | "در تماس" | "مذاکره" | "مشتری فعال" | "وفادار" | "ریزش";
type Activity = { id: string; type: "یادداشت" | "تماس" | "پیام"; text: string; at: string };
type Task = { id: string; title: string; due: string; done: boolean };
type CRMCustomer = { name: string; phone: string; email: string; city: string; orders: number; total: number; lastOrder: string; stage: Stage; owner: string; tags: string[]; consent: boolean; activities: Activity[]; tasks: Task[] };

const key = "kv_admin_crm_v1";
const stages: Stage[] = ["سرنخ", "در تماس", "مذاکره", "مشتری فعال", "وفادار", "ریزش"];
const seed: CRMCustomer[] = [
  { name:"امیرحسین رضایی",phone:"۰۹۱۲۳۴۵۶۷۸۹",email:"amir@example.com",city:"تهران",orders:7,total:24_500_000,lastOrder:"۱۲ مرداد",stage:"وفادار",owner:"مریم احمدی",tags:["ارزش بالا","استایل کلاسیک"],consent:true,activities:[{id:"a1",type:"تماس",text:"پیگیری رضایت از سفارش بلیزر انجام شد.",at:"امروز · ۱۰:۲۰"}],tasks:[{id:"t1",title:"ارسال پیشنهاد کالکشن پاییز",due:"فردا",done:false}] },
  { name:"سهیل مرادی",phone:"۰۹۱۲۹۸۷۶۵۴۳",email:"soheil@example.com",city:"کرج",orders:4,total:12_800_000,lastOrder:"۱۲ مرداد",stage:"مشتری فعال",owner:"علی نوری",tags:["خرید آنلاین"],consent:true,activities:[{id:"a2",type:"پیام",text:"راهنمای انتخاب سایز ارسال شد.",at:"دیروز · ۱۶:۴۰"}],tasks:[] },
  { name:"نیما صادقی",phone:"۰۹۱۳۱۱۲۲۳۳۴",email:"nima@example.com",city:"اصفهان",orders:3,total:8_400_000,lastOrder:"۱۱ مرداد",stage:"در تماس",owner:"مریم احمدی",tags:["پیگیری سایز"],consent:true,activities:[],tasks:[{id:"t2",title:"تماس درباره تعویض سایز",due:"امروز",done:false}] },
  { name:"بابک کریمی",phone:"۰۹۱۴۵۵۶۶۷۷۸",email:"babak@example.com",city:"تبریز",orders:2,total:9_100_000,lastOrder:"۱۱ مرداد",stage:"مذاکره",owner:"علی نوری",tags:["عمده بالقوه"],consent:false,activities:[],tasks:[] },
];
const load = () => { try { const raw=localStorage.getItem(key); return raw ? JSON.parse(raw) as CRMCustomer[] : seed; } catch { return seed; } };
const field="h-10 w-full rounded-lg border border-neutral-300 bg-white px-3 text-[11px] outline-none focus-visible:ring-2 focus-visible:ring-[#011c3a]";

export default function AdminCRM(){
  const [customers,setCustomers]=useState(load);
  const [view,setView]=useState<"overview"|"customers"|"pipeline"|"tasks">("overview");
  const [query,setQuery]=useState("");
  const [stage,setStage]=useState("همه");
  const [selectedPhone,setSelectedPhone]=useState<string|null>(null);
  const [note,setNote]=useState("");
  const [taskTitle,setTaskTitle]=useState("");
  const [saved,setSaved]=useState(false);
  const persist=(next:CRMCustomer[])=>{setCustomers(next);localStorage.setItem(key,JSON.stringify(next));setSaved(true);setTimeout(()=>setSaved(false),1200);};
  const selected=customers.find(c=>c.phone===selectedPhone)??null;
  const filtered=useMemo(()=>customers.filter(c=>(stage==="همه"||c.stage===stage)&&(`${c.name} ${c.phone} ${c.email} ${c.city} ${c.tags.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()))),[customers,query,stage]);
  const pending=customers.flatMap(c=>c.tasks.filter(t=>!t.done).map(t=>({...t,customer:c.name,phone:c.phone})));
  const update=(phone:string,patch:Partial<CRMCustomer>)=>persist(customers.map(c=>c.phone===phone?{...c,...patch}:c));
  const addActivity=(type:Activity["type"])=>{if(!selected||!note.trim())return;update(selected.phone,{activities:[{id:crypto.randomUUID(),type,text:note.trim(),at:new Intl.DateTimeFormat("fa-IR",{dateStyle:"short",timeStyle:"short"}).format(new Date())},...selected.activities]});setNote("");};
  const addTask=()=>{if(!selected||!taskTitle.trim())return;update(selected.phone,{tasks:[...selected.tasks,{id:crypto.randomUUID(),title:taskTitle.trim(),due:"بدون موعد",done:false}]});setTaskTitle("");};

  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] tracking-[0.25em] text-neutral-400">CUSTOMER RELATIONSHIP MANAGEMENT</p><h1 className="mt-2 text-[22px] font-medium">مرکز ارتباط با مشتری</h1><p className="mt-2 text-[11px] text-neutral-500">فروش، ارتباطات، پیگیری و ارزش طول عمر مشتری در یک نمای واحد.</p></div><div className="flex gap-2"><button onClick={()=>{const name=prompt("نام مشتری جدید");if(name)persist([{name,phone:"",email:"",city:"",orders:0,total:0,lastOrder:"—",stage:"سرنخ",owner:"تخصیص‌نیافته",tags:[],consent:false,activities:[],tasks:[]},...customers]);}} className="h-10 rounded-lg bg-[#011c3a] px-4 text-[11px] text-white">+ مشتری جدید</button></div></div>
    {saved&&<p role="status" className="mt-4 rounded-lg border border-[#b9cfbc] bg-[#edf3ee] px-3 py-2 text-[10px] text-[#36563a]">تغییرات CRM ذخیره شد.</p>}
    <nav className="mt-5 flex gap-2 overflow-x-auto border-b border-neutral-200 pb-3">{([["overview","نمای کلی"],["customers","مشتریان"],["pipeline","قیف ارتباط"],["tasks","پیگیری‌ها"]] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={(view===id?"bg-[#011c3a] text-white":"border border-neutral-300 bg-white")+" shrink-0 rounded-lg px-4 py-2 text-[11px]"}>{label}</button>)}</nav>

    {view==="overview"&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["کل مشتریان",fa(customers.length)],["ارزش ثبت‌شده",toman(customers.reduce((s,c)=>s+c.total,0))],["پیگیری باز",fa(pending.length)],["مشتریان وفادار",fa(customers.filter(c=>c.stage==="وفادار").length)]].map(([label,value])=><article key={label} className="rounded-xl border border-neutral-200 bg-white p-4"><p className="text-[10px] text-neutral-500">{label}</p><p className="mt-2 text-[19px] font-medium num-fa">{value}</p></article>)}</div><div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="text-[12px] font-medium">توزیع مشتریان در قیف</h2><div className="mt-4 space-y-3">{stages.map(s=>{const count=customers.filter(c=>c.stage===s).length;return <div key={s}><div className="flex justify-between text-[10px]"><span>{s}</span><span className="num-fa">{fa(count)}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-neutral-100"><span className="block h-full rounded-full bg-[#011c3a]" style={{width:`${customers.length?Math.max(4,count/customers.length*100):0}%`}}/></div></div>})}</div></section><section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="text-[12px] font-medium">پیگیری‌های نزدیک</h2><div className="mt-3 divide-y divide-neutral-100">{pending.slice(0,5).map(t=><button key={t.id} onClick={()=>{setSelectedPhone(t.phone);setView("customers")}} className="flex w-full items-center justify-between gap-3 py-3 text-right"><span><strong className="block text-[10.5px] font-medium">{t.title}</strong><small className="mt-1 block text-[9px] text-neutral-400">{t.customer}</small></span><span className="text-[9px] text-neutral-500">{t.due}</span></button>)}{!pending.length&&<p className="py-8 text-center text-[10px] text-neutral-400">پیگیری بازی وجود ندارد.</p>}</div></section></div></div>}

    {view==="customers"&&<div className="mt-5"><div className="grid gap-3 rounded-xl border border-neutral-200 bg-white p-3 sm:grid-cols-[1fr_180px]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام، موبایل، شهر یا برچسب" className={field}/><select value={stage} onChange={e=>setStage(e.target.value)} className={field}><option>همه</option>{stages.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-4 overflow-x-auto rounded-xl border border-neutral-200 bg-white"><table className="w-full min-w-[780px] text-right text-[10.5px]"><thead className="bg-neutral-50 text-neutral-500"><tr>{["مشتری","مرحله","مسئول","آخرین خرید","سفارش","ارزش",""].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(c=><tr key={c.phone} className="border-t border-neutral-100 hover:bg-neutral-50"><td className="p-3"><strong className="font-medium">{c.name}</strong><span className="mt-1 block text-[9px] text-neutral-400 num-fa">{c.phone} · {c.city}</span></td><td className="p-3"><select value={c.stage} onChange={e=>update(c.phone,{stage:e.target.value as Stage})} className="rounded-md border border-neutral-200 px-2 py-1.5">{stages.map(s=><option key={s}>{s}</option>)}</select></td><td className="p-3">{c.owner}</td><td className="p-3">{c.lastOrder}</td><td className="p-3 num-fa">{fa(c.orders)}</td><td className="p-3 num-fa">{toman(c.total)}</td><td className="p-3"><button onClick={()=>setSelectedPhone(c.phone)} className="rounded-md border border-neutral-300 px-3 py-1.5">پروفایل ۳۶۰</button></td></tr>)}</tbody></table></div></div>}

    {view==="pipeline"&&<div className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6">{stages.map(s=><section key={s} className="rounded-xl border border-neutral-200 bg-white p-3"><div className="flex justify-between"><h2 className="text-[11px] font-medium">{s}</h2><span className="text-[9px] text-neutral-400 num-fa">{fa(customers.filter(c=>c.stage===s).length)}</span></div><div className="mt-3 space-y-2">{customers.filter(c=>c.stage===s).map(c=><button key={c.phone} onClick={()=>setSelectedPhone(c.phone)} className="w-full rounded-lg border border-neutral-100 bg-neutral-50 p-3 text-right"><strong className="text-[10.5px] font-medium">{c.name}</strong><span className="mt-1 block text-[9px] text-neutral-400 num-fa">{toman(c.total)}</span></button>)}</div></section>)}</div>}

    {view==="tasks"&&<div className="mt-5 rounded-xl border border-neutral-200 bg-white p-5"><h2 className="text-[13px] font-medium">همه پیگیری‌ها</h2><div className="mt-3 divide-y divide-neutral-100">{customers.flatMap(c=>c.tasks.map(t=>({t,c}))).map(({t,c})=><label key={t.id} className="flex items-center gap-3 py-3"><input type="checkbox" checked={t.done} onChange={()=>update(c.phone,{tasks:c.tasks.map(item=>item.id===t.id?{...item,done:!item.done}:item)})}/><span className="flex-1"><strong className={(t.done?"line-through text-neutral-400":"")+" block text-[10.5px] font-medium"}>{t.title}</strong><small className="mt-1 block text-[9px] text-neutral-400">{c.name} · {t.due}</small></span><button onClick={()=>setSelectedPhone(c.phone)} className="text-[9.5px] underline">پروفایل</button></label>)}</div></div>}

    {selected&&<div className="fixed inset-0 z-50 bg-black/35" onClick={()=>setSelectedPhone(null)}><aside className="absolute inset-y-0 left-0 w-full max-w-xl overflow-y-auto bg-white p-5 sm:p-7" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-[9px] tracking-[.2em] text-neutral-400">CUSTOMER 360</p><h2 className="mt-2 text-[20px] font-medium">{selected.name}</h2><p className="mt-1 text-[10px] text-neutral-500 num-fa">{selected.phone} · {selected.email}</p></div><button onClick={()=>setSelectedPhone(null)} aria-label="بستن" className="h-9 w-9 rounded-full border border-neutral-300"><Icon name="close" className="h-4 w-4"/></button></div><div className="mt-5 grid grid-cols-3 gap-2">{[["سفارش",fa(selected.orders)],["ارزش",toman(selected.total)],["مرحله",selected.stage]].map(([a,b])=><div key={a} className="rounded-lg bg-neutral-50 p-3"><p className="text-[9px] text-neutral-400">{a}</p><p className="mt-1 text-[10px] font-medium num-fa">{b}</p></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-neutral-500">مرحله<select value={selected.stage} onChange={e=>update(selected.phone,{stage:e.target.value as Stage})} className={field+" mt-1"}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-[10px] text-neutral-500">مسئول<input value={selected.owner} onChange={e=>update(selected.phone,{owner:e.target.value})} className={field+" mt-1"}/></label></div><section className="mt-6"><h3 className="text-[12px] font-medium">ثبت تعامل</h3><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="خلاصه تماس، پیام یا یادداشت داخلی" className={field+" mt-3 h-auto py-3"}/><div className="mt-2 flex gap-2">{(["یادداشت","تماس","پیام"] as const).map(type=><button key={type} onClick={()=>addActivity(type)} className="rounded-lg border border-neutral-300 px-3 py-2 text-[10px]">ثبت {type}</button>)}</div></section><section className="mt-6"><h3 className="text-[12px] font-medium">پیگیری بعدی</h3><div className="mt-3 flex gap-2"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="مثلاً تماس برای تمدید خرید" className={field}/><button onClick={addTask} className="shrink-0 rounded-lg bg-[#011c3a] px-4 text-[10px] text-white">افزودن</button></div></section><section className="mt-6"><h3 className="text-[12px] font-medium">تاریخچه ارتباط</h3><div className="mt-3 divide-y divide-neutral-100">{selected.activities.map(a=><article key={a.id} className="py-3"><div className="flex justify-between"><strong className="text-[10px] font-medium">{a.type}</strong><span className="text-[9px] text-neutral-400">{a.at}</span></div><p className="mt-1.5 text-[10.5px] leading-[1.8] text-neutral-600">{a.text}</p></article>)}{!selected.activities.length&&<p className="py-6 text-center text-[10px] text-neutral-400">هنوز تعاملی ثبت نشده است.</p>}</div></section></aside></div>}
  </div>;
}
