export const PORTALS = ["PUBLIC_STOREFRONT", "RETAIL_CUSTOMER", "VIP_WHOLESALE", "SUPPLIER", "ADMIN", "CMS_EDITOR", "SHARED"] as const;
export const TRUTH_CLASSIFICATIONS = ["CANONICAL_API", "COMPAT_PROXY", "LOCAL_STORAGE", "STATIC_FIXTURE", "HARDCODED_RUNTIME", "MIXED", "PRESENTATION_DEFAULT", "BROWSER_EPHEMERAL", "DEPRECATED", "UNKNOWN"] as const;
export const PRESERVATION_POLICIES = ["KEEP", "UPGRADE", "MERGE_NO_LOSS", "RENAME_REORGANIZE", "REPLACE_WITH_CORRECT_IMPLEMENTATION", "DELETE_PROVEN_DUPLICATE"] as const;
export const BACKEND_OWNERS = ["auth", "catalog", "pricing", "promotions", "inventory", "orders", "payments", "shipping", "returns", "ratings", "search", "vip", "suppliers", "supplier-team", "production", "admin", "crm", "support", "notifications", "cms", "analytics", "audit", "compliance", "settlement", "finance", "invoicing", "operational-telemetry"] as const;
/**
 * CONTROLLED DESIGN EVOLUTION (replaces the retired Hard Design Freeze).
 *
 * The Hard Design Freeze applied to the original Phase 6.0-6.2 truth cutover:
 * while backend truth was being moved off the browser, page composition and
 * navigation had to stay byte-stable so that every diff was provably about
 * data ownership. That migration is finished for the migrated surfaces, so the
 * freeze is retired - but NOT deleted, because "anything may change" is not a
 * governance model either.
 *
 * Every registry surface now carries exactly one deliberate policy:
 *
 * - PRESERVE     current structure already serves the workflow. Only wiring,
 *                states, correctness and small usability fixes are allowed.
 * - EXTEND       keep the existing visual/interaction language, add the
 *                missing backend-supported capabilities.
 * - RESTRUCTURE  the current information architecture or interaction model
 *                prevents a complete, usable workflow. Structural redesign is
 *                allowed while retaining Kolbe identity - and it must be
 *                justified in writing (`designChangeRationale`).
 *
 * Design freedom is not architecture freedom: backend truth, domain ownership,
 * business invariants, the Kolbe brand identity and the semantic token system
 * remain authoritative under every policy.
 */
export const DESIGN_CHANGE_POLICIES = ["PRESERVE", "EXTEND", "RESTRUCTURE"] as const;

export const UI_STATES = ["LOADING", "READY_WITH_DATA", "READY_EMPTY", "VALIDATION_ERROR", "UNAUTHORIZED", "FORBIDDEN", "NOT_FOUND", "CONFLICT", "RATE_LIMITED", "SERVER_ERROR", "NETWORK_ERROR", "PROVIDER_UNAVAILABLE"] as const;

export type Portal = typeof PORTALS[number];
export type TruthClassification = typeof TRUTH_CLASSIFICATIONS[number];
export type PreservationPolicy = typeof PRESERVATION_POLICIES[number];
export type BackendOwner = typeof BACKEND_OWNERS[number];
export type UiState = typeof UI_STATES[number];
export type DesignChangePolicy = typeof DESIGN_CHANGE_POLICIES[number];
export type Pagination = "NONE" | "OFFSET" | "KEYSET" | "CURSOR";
export type CutoverPhase = "6.1" | "6.2" | "6.3" | "6.4" | "6.5" | "6.6" | "6.7";

export type ApiContract = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  request: string;
  response: string;
  actor: string;
  permission: string | null;
  pagination: Pagination;
  errors: string[];
};

export type FrontendTruthEntry = {
  id: string;
  portal: Portal;
  feature: string;
  routesOrPages: string[];
  sourceFiles: string[];
  currentTruthSource: string;
  classification: TruthClassification;
  businessTruth: boolean;
  canonicalBackendOwner: BackendOwner;
  canonicalApiContracts: ApiContract[];
  compatibilityRoutes: string[];
  cutoverPhase: CutoverPhase;
  preservationPolicy: PreservationPolicy;
  parityTests: string[];
  uiStates: UiState[];
  designChangePolicy: DesignChangePolicy;
  /** Required in practice for RESTRUCTURE; enforced by the registry test. */
  designChangeRationale?: string;
  moneySemantics?: "NOT_APPLICABLE" | "DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY";
  identityAuthority?: "SERVER_SESSION" | "NOT_APPLICABLE";
  channelOwnership?: "RETAIL_KOLBE" | "WHOLESALE_KOLBE_AND_SUPPLIERS" | "NOT_APPLICABLE";
  decomposition?: string;
  duplicateEvidence?: string;
  notes: string;
};

const standardStates: UiState[] = ["LOADING", "READY_WITH_DATA", "READY_EMPTY", "UNAUTHORIZED", "FORBIDDEN", "SERVER_ERROR", "NETWORK_ERROR"];
const publicStates: UiState[] = ["LOADING", "READY_WITH_DATA", "READY_EMPTY", "NOT_FOUND", "RATE_LIMITED", "SERVER_ERROR", "NETWORK_ERROR"];

function contract(path: string, actor: string, pagination: Pagination = "NONE", permission: string | null = null, method: ApiContract["method"] = "GET"): ApiContract {
  return { method, path, request: method === "GET" ? "path/query DTO" : "validated command DTO; identity fields ignored or derived", response: pagination === "NONE" ? "typed resource/command result" : "typed items plus canonical pagination metadata", actor, permission, pagination, errors: ["VALIDATION_ERROR", "UNAUTHORIZED", "FORBIDDEN", "NOT_FOUND", "CONFLICT", "RATE_LIMITED", "SERVER_ERROR", "PROVIDER_UNAVAILABLE"] };
}

type Seed = Omit<FrontendTruthEntry, "uiStates" | "moneySemantics" | "identityAuthority" | "channelOwnership"> & Partial<Pick<FrontendTruthEntry, "uiStates" | "moneySemantics" | "identityAuthority" | "channelOwnership">>;
const entry = (seed: Seed): FrontendTruthEntry => ({
  ...seed,
  uiStates: seed.uiStates ?? standardStates,
  designChangeRationale: seed.designChangeRationale,
  moneySemantics: seed.moneySemantics ?? "NOT_APPLICABLE",
  identityAuthority: seed.identityAuthority ?? "SERVER_SESSION",
  channelOwnership: seed.channelOwnership ?? "NOT_APPLICABLE",
});

export const FRONTEND_TRUTH_REGISTRY: FrontendTruthEntry[] = [
  entry({ designChangePolicy:"PRESERVE", id:"shared-auth-session", portal:"SHARED", feature:"Customer, VIP, Supplier and Admin session lifecycle", routesOrPages:["all protected routes"], sourceFiles:["storefront/lib/api.ts","storefront/lib/siteAuthApi.ts","storefront/lib/wholesaleApi.ts","storefront/lib/wholesaleVipApi.ts","supplier-src/api.ts"], currentTruthSource:"HttpOnly session through duplicated compatibility clients", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"auth", canonicalApiContracts:[contract("/api/v1/auth/login","public", "NONE", null,"POST"),contract("/api/v1/auth/logout","session","NONE",null,"POST"),contract("/api/v1/auth/me","session")], compatibilityRoutes:["POST /store/kolbe/auth/login","POST /store/kolbe/auth/logout","GET /store/kolbe/auth/me","POST /store/kolbe/supplier/auth/login","GET /store/kolbe/supplier/session"], cutoverPhase:"6.1", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/session-security.test.ts","test/auth-cutover.test.ts","test/phase-6-1-api-client.test.ts","test/phase-6-1-auth-session.test.ts","test/phase-6-1-live-contract.test.ts"], notes:"Phase 6.1 delivers one shared HTTP/session boundary; the portal clients themselves migrate in 6.2-6.6. Role, user, supplier tenant, VIP account and Admin permissions always come from the server session." }),
  entry({ designChangePolicy:"PRESERVE", id:"shared-frontend-boundary", portal:"SHARED", feature:"Shared typed API, session, error, pagination, money, permission and design-token boundary", routesOrPages:["all portals"], sourceFiles:["shared/http/client.ts","shared/http/errors.ts","shared/session/auth-client.ts","shared/session/store.ts","shared/ui/async-state.ts","shared/pagination/pagination.ts","shared/money/money.ts","shared/permissions/capabilities.ts","shared/design/tokens.ts","shared/design/tokens.css","shared/design/foundation.css"], currentTruthSource:"shared typed boundary over the canonical Nest API", classification:"CANONICAL_API", businessTruth:false, canonicalBackendOwner:"auth", canonicalApiContracts:[contract("/api/v1/auth/me","session")], compatibilityRoutes:[], cutoverPhase:"6.1", preservationPolicy:"KEEP", parityTests:["test/phase-6-1-api-client.test.ts","test/phase-6-1-auth-session.test.ts","test/phase-6-1-ui-state.test.ts","test/phase-6-1-pagination.test.ts","test/phase-6-1-money.test.ts","test/phase-6-1-permissions.test.ts","test/phase-6-1-design-tokens.test.ts","test/phase-6-1-boundary-guard.test.ts"], uiStates:["LOADING","READY_WITH_DATA","READY_EMPTY","VALIDATION_ERROR","UNAUTHORIZED","FORBIDDEN","NOT_FOUND","CONFLICT","RATE_LIMITED","SERVER_ERROR","NETWORK_ERROR","PROVIDER_UNAVAILABLE"], identityAuthority:"SERVER_SESSION", decomposition:"Generic transport stays separate from portal feature adapters; portal feature adapters arrive with each portal cutover.", notes:"Phase 6.1 added this entry to keep the registry the single source of truth. It introduces no visual, schema or backend-ownership change and migrates no portal feature." }),
  entry({ designChangePolicy:"PRESERVE", id:"public-home-cms", portal:"PUBLIC_STOREFRONT", feature:"Home, hero, navigation and editorial sections", routesOrPages:["/","Home","Static","Styles"], sourceFiles:["storefront/pages/Home.tsx","storefront/pages/Static.tsx","storefront/pages/Styles.tsx","storefront/siteData.ts","storefront/siteSettings.ts","storefront/components/HomepageHero.tsx","storefront/components/SiteHeader.tsx","storefront/components/SiteFooter.tsx"], currentTruthSource:"embedded presentation defaults plus CMS remote settings and editor cache", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"cms", canonicalApiContracts:[contract("/api/v1/cms/public/site-settings","public")], compatibilityRoutes:["GET /store/kolbe/site/settings"], cutoverPhase:"6.6", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-6-home-cms-parity"], uiStates:publicStates, identityAuthority:"NOT_APPLICABLE", decomposition:"Keep embedded presentation fallback and theme; replace published content authority with CMS; retain browser copy only as editor cache.", notes:"Visual layout, RTL and content slots are frozen." }),
  entry({ designChangePolicy:"PRESERVE", id:"public-blog", portal:"PUBLIC_STOREFRONT", feature:"Journal/blog publication and homepage pins", routesOrPages:["/blog","Blog"], sourceFiles:["storefront/pages/Blog.tsx","storefront/journalSettings.ts"], currentTruthSource:"localStorage articles and pins", classification:"LOCAL_STORAGE", businessTruth:true, canonicalBackendOwner:"cms", canonicalApiContracts:[contract("/api/v1/cms/public/articles","public","CURSOR")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-6-blog-publication"], uiStates:publicStates, identityAuthority:"NOT_APPLICABLE", notes:"Publication truth moves to CMS; pins remain an editorial relation." }),
  entry({ designChangePolicy:"PRESERVE", id:"public-legal-policies", portal:"PUBLIC_STOREFRONT", feature:"Legal and retail policy publication", routesOrPages:["/legal","Legal","RetailPolicyCenter"], sourceFiles:["storefront/pages/Legal.tsx","storefront/pages/RetailPolicyCenter.tsx"], currentTruthSource:"embedded policy presentation", classification:"PRESENTATION_DEFAULT", businessTruth:true, canonicalBackendOwner:"cms", canonicalApiContracts:[contract("/api/v1/cms/public/policies/:slug","public")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"UPGRADE", parityTests:["test/retail-legal-gate.test.ts","planned:phase-6-6-legal-content"], uiStates:publicStates, identityAuthority:"NOT_APPLICABLE", notes:"Published policy content moves to CMS while legal acceptance evidence remains backend-owned." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-catalog-browse", portal:"PUBLIC_STOREFRONT", feature:"Shop, category, collection and product cards", routesOrPages:["/shop","/collection/:slug","Shop","Collection"], sourceFiles:["storefront/pages/Shop.tsx","storefront/pages/Collection.tsx","storefront/components/ProductCard.tsx","storefront/data/catalog.ts"], currentTruthSource:"large static catalog fixture with local admin overlay", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/store/catalog/products","public","CURSOR")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-6-catalog-grid"], uiStates:publicStates, channelOwnership:"RETAIL_KOLBE", decomposition:"Catalog data becomes API authority; fixture remains only as explicit development/demo data until Phase 6.7.", notes:"Retail seller remains KOLBE." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-search-discovery", portal:"PUBLIC_STOREFRONT", feature:"Search, filters, taxonomy and discovery", routesOrPages:["/shop?q=","Shop filters","CatalogTaxonomyManager"], sourceFiles:["storefront/pages/Shop.tsx","storefront/lib/catalogTaxonomy.ts","storefront/pages/CatalogTaxonomyManager.tsx"], currentTruthSource:"client filtering plus hardcoded taxonomy", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"search", canonicalApiContracts:[contract("/api/v1/search/products","public","CURSOR")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-6-search-discovery"], uiStates:publicStates, channelOwnership:"RETAIL_KOLBE", notes:"Canonical filters and pagination replace load-all assumptions." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-product-detail", portal:"PUBLIC_STOREFRONT", feature:"Product detail, media, variants and specifications", routesOrPages:["/product/:slug","ProductPage","DynamicProductSpecifications"], sourceFiles:["storefront/pages/ProductPage.tsx","storefront/pages/DynamicProductSpecifications.tsx","storefront/pages/ProductMediaStudio.tsx","storefront/productSchemas.ts"], currentTruthSource:"static fixture and local admin product overlay", classification:"STATIC_FIXTURE", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/store/catalog/products/:slug","public")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-6-product-detail"], uiStates:publicStates, channelOwnership:"RETAIL_KOLBE", notes:"Media and specifications remain visually identical." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-ratings-reviews", portal:"PUBLIC_STOREFRONT", feature:"Ratings and reviews", routesOrPages:["ProductPage reviews"], sourceFiles:["storefront/pages/ProductPage.tsx"], currentTruthSource:"embedded product review presentation", classification:"STATIC_FIXTURE", businessTruth:true, canonicalBackendOwner:"ratings", canonicalApiContracts:[contract("/api/v1/ratings/products/:productId/reviews","public","CURSOR")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-6-ratings-reviews"], uiStates:publicStates, notes:"Moderation and eligibility remain backend-owned." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-cart", portal:"RETAIL_CUSTOMER", feature:"Cart and cart drawer", routesOrPages:["/cart","Cart","CartDrawer"], sourceFiles:["storefront/pages/Cart.tsx","storefront/components/CartDrawer.tsx","storefront/store.tsx"], currentTruthSource:"kv_cart browser draft with client display totals", classification:"BROWSER_EPHEMERAL", businessTruth:false, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/store/checkout/quote","customer session","NONE",null,"POST")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"UPGRADE", parityTests:["test/retail-checkout.test.ts","planned:phase-6-6-cart-quote"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"RETAIL_KOLBE", notes:"A local draft may persist, but price, discount, stock and payable total are never authoritative in the browser." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-wishlist-compare", portal:"RETAIL_CUSTOMER", feature:"Wishlist and compare", routesOrPages:["header wishlist","compare bar"], sourceFiles:["storefront/store.tsx","storefront/components/CompareBar.tsx"], currentTruthSource:"kv_wish and kv_compare browser preferences", classification:"BROWSER_EPHEMERAL", businessTruth:false, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/store/account/wishlist","customer session")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"KEEP", parityTests:["planned:phase-6-6-wishlist-compare"], notes:"Compare is presentation state; authenticated wishlist may synchronize without making browser identity authoritative." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-checkout", portal:"RETAIL_CUSTOMER", feature:"Checkout, authoritative quote and order placement", routesOrPages:["/checkout","Checkout"], sourceFiles:["storefront/pages/Checkout.tsx","server/retail-pricing.ts","server/money-input.ts"], currentTruthSource:"compatibility API backed by canonical Retail Orders", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/store/checkout","customer session","NONE",null,"POST")], compatibilityRoutes:["POST /store/kolbe/checkout"], cutoverPhase:"6.6", preservationPolicy:"UPGRADE", parityTests:["test/retail-checkout.test.ts","test/retail-payment-honesty.test.ts"], uiStates:[...standardStates,"VALIDATION_ERROR","CONFLICT","PROVIDER_UNAVAILABLE"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"RETAIL_KOLBE", notes:"Client totals are advisory; server quote and order response are authoritative." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-account-identity", portal:"RETAIL_CUSTOMER", feature:"Login, profile and customer identity", routesOrPages:["account modal","protected retail pages"], sourceFiles:["storefront/customerIdentity.ts","storefront/lib/siteAuthApi.ts","storefront/App.tsx"], currentTruthSource:"server session plus kv_customer display cache", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"auth", canonicalApiContracts:[contract("/api/v1/auth/me","customer session")], compatibilityRoutes:["GET /store/kolbe/me"], cutoverPhase:"6.1", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/session-hardening.test.ts","test/phase-6-1-auth-session.test.ts","planned:phase-6-6-retail-session-wiring"], decomposition:"Server owns ID and role; browser cache may retain display-only fields after validation.", notes:"Phase 6.1 provides the shared session primitive; browser customer ID is never authority." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-orders-after-sales", portal:"RETAIL_CUSTOMER", feature:"Orders, returns, refund status and support", routesOrPages:["account orders","returns","support"], sourceFiles:["storefront/App.tsx","storefront/pages/RetailPolicyCenter.tsx"], currentTruthSource:"partial canonical capability proxy and policy presentation", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"returns", canonicalApiContracts:[contract("/api/v1/store/account/orders","customer session","KEYSET"),contract("/api/v1/store/returns","customer session","NONE",null,"POST")], compatibilityRoutes:["GET/POST /store/kolbe/account/*"], cutoverPhase:"6.6", preservationPolicy:"UPGRADE", parityTests:["test/phase-5-9-a-retail-capability-proxy.test.ts","planned:phase-6-6-after-sales"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"Refund state remains server-derived." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-promotions", portal:"PUBLIC_STOREFRONT", feature:"Promotion display, promo popup and campaign eligibility", routesOrPages:["Home promotions","PromoPopup","Cart discount"], sourceFiles:["storefront/components/PromoPopup.tsx","storefront/siteData.ts","storefront/pages/Cart.tsx"], currentTruthSource:"hardcoded presentation mixed with server checkout evaluation", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"promotions", canonicalApiContracts:[contract("/api/v1/store/promotions/eligible","public","CURSOR")], compatibilityRoutes:[], cutoverPhase:"6.6", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-6-promotions"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", decomposition:"CMS controls artwork/copy; Promotions controls eligibility, discount and attribution.", notes:"Campaign visuals do not own commercial truth." }),
  entry({ designChangePolicy:"PRESERVE", id:"retail-try-on", portal:"PUBLIC_STOREFRONT", feature:"Virtual try-on upload, task and result", routesOrPages:["/try-on","TryOn"], sourceFiles:["storefront/pages/TryOn.tsx","server/perfect-corp.ts","server/try-on-guard.ts"], currentTruthSource:"bounded Next provider edge", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/store/try-on/tasks","public","NONE",null,"POST")], compatibilityRoutes:["POST /store/kolbe/try-on/files","POST /store/kolbe/try-on/tasks","GET /store/kolbe/try-on/tasks/:id","POST /store/kolbe/try-on/download"], cutoverPhase:"6.6", preservationPolicy:"KEEP", parityTests:["test/try-on-guard.test.ts"], uiStates:[...publicStates,"PROVIDER_UNAVAILABLE","VALIDATION_ERROR"], identityAuthority:"NOT_APPLICABLE", notes:"Provider availability must be truthful; transport remains a classified edge." }),

  entry({ designChangePolicy:"PRESERVE", designChangeRationale:"Server-authoritative VIP session and the membership-vs-entitlement separation are correct and are the security boundary for 6.3-C; the shell is preserved.", id:"vip-membership", portal:"VIP_WHOLESALE", feature:"VIP application, membership and session", routesOrPages:["/vip","VIPPortal"], sourceFiles:["storefront/pages/VIPPortal.tsx","storefront/lib/wholesaleVipApi.ts","storefront/wholesaleMembership.ts"], currentTruthSource:"canonical VIP through compatibility API plus obsolete local membership cache", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"vip", canonicalApiContracts:[contract("/api/v1/vip/compat/applications","customer session","NONE",null,"POST"),contract("/api/v1/compat/wholesale/account","customer/VIP session")], compatibilityRoutes:["POST /store/kolbe/wholesale/apply","GET /store/kolbe/wholesale/account"], cutoverPhase:"6.3", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/vip-membership.test.ts","planned:phase-6-3-vip-membership"], decomposition:"Server owns membership status and account identity; remove kv_wholesale_membership as authority.", notes:"VIP account ID derives from session." }),
  entry({ designChangePolicy:"RESTRUCTURE", designChangeRationale:"The wholesale catalog rendered products without the commercial truth a VIP buyer must act on: seller identity, variant selection, MOQ with its real unit, SERIES/package composition and pricing tiers were all absent, so a buyer could not distinguish a SERIES offer from a per-piece one. The card/preview information architecture is being restructured to expose that truth; pagination stays canonical cursor-based and entitlement rules are unchanged.", id:"vip-wholesale-catalog", portal:"VIP_WHOLESALE", feature:"Wholesale catalog, packages and tiers", routesOrPages:["/wholesale","/vip/catalog","/vip/store","Wholesale","WholesaleCatalog"], sourceFiles:["storefront/pages/Wholesale.tsx","storefront/pages/VIPPortal.tsx","storefront/pages/WholesaleCatalog.tsx","storefront/lib/wholesaleVipApi.ts","shared/wholesale/catalog.ts"], currentTruthSource:"canonical /catalog/browse + /catalog/products/:id via the shared wholesale adapter", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/catalog/browse","active VIP (catalog entitlement)","CURSOR"),contract("/api/v1/catalog/products/:id","active VIP (catalog entitlement)"),contract("/api/v1/compat/wholesale/products","active VIP","CURSOR")], compatibilityRoutes:["GET /store/kolbe/wholesale/products"], cutoverPhase:"6.3", preservationPolicy:"UPGRADE", parityTests:["test/phase-6-3-wholesale-catalog.test.ts","test/phase-6-3-wholesale-catalog-ui.test.tsx","e2e/phase-6-3-wholesale-catalog-l5.mjs"], decomposition:"CANONICAL: /vip/catalog list + /vip/catalog/:id detail read /catalog/browse and /catalog/products/:id through shared/wholesale/catalog.ts (decimal-string money, cursor pagination, MOQ unit, package composition, pricing tiers). COMPAT/LEGACY: /vip/store, /vip/quick-order and the VIP dashboard still render storefront/data/catalog fixtures with a browser-computed wholesale price and hardcoded pack sizes; they remain only because the local pre-order draft and wholesale_customer_order flow depend on that fixture shape. That residue is the remaining 6.3-C cleanup and is tracked, not hidden.", moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"WHOLESALE_KOLBE_AND_SUPPLIERS", notes:"Wholesale sellers remain KOLBE plus Suppliers." }),
  entry({ designChangePolicy:"PRESERVE", id:"vip-wholesale-orders", portal:"VIP_WHOLESALE", feature:"Wholesale draft, order creation, payment and shipping state", routesOrPages:["/vip/orders","WholesaleDashboard"], sourceFiles:["storefront/pages/WholesaleDashboard.tsx","storefront/lib/wholesaleVipApi.ts"], currentTruthSource:"canonical order API mixed with local draft and legacy local submitted-order history", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/wholesale/orders","active VIP","NONE",null,"POST"),contract("/api/v1/compat/wholesale/orders","active VIP","KEYSET")], compatibilityRoutes:["GET /store/kolbe/wholesale/orders","POST /store/kolbe/wholesale/orders"], cutoverPhase:"6.3", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-3-wholesale-orders"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"WHOLESALE_KOLBE_AND_SUPPLIERS", decomposition:"Local draft is ephemeral; submitted order/payment/shipping truth comes only from Orders/Payments/Shipping APIs.", notes:"Date.now order codes are removed only during cutover." }),
  entry({ designChangePolicy:"PRESERVE", id:"vip-rfq-offers", portal:"VIP_WHOLESALE", feature:"Wholesale RFQ/request and offer flows", routesOrPages:["VIP request views","Wholesale"], sourceFiles:["storefront/pages/VIPPortal.tsx","storefront/pages/Wholesale.tsx"], currentTruthSource:"partial hardcoded runtime", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"vip", canonicalApiContracts:[contract("/api/v1/vip/requests","active VIP","CURSOR"),contract("/api/v1/vip/requests/:id/offers","active VIP")], compatibilityRoutes:[], cutoverPhase:"6.3", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-3-vip-rfq"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"WHOLESALE_KOLBE_AND_SUPPLIERS", notes:"Offer prices and request lifecycle are server authority." }),
  entry({ designChangePolicy:"PRESERVE", id:"vip-support-team", portal:"VIP_WHOLESALE", feature:"VIP support and account team", routesOrPages:["VIP support","VIP account"], sourceFiles:["storefront/pages/VIPPortal.tsx","storefront/wholesaleSupport.ts"], currentTruthSource:"localStorage ticket history", classification:"LOCAL_STORAGE", businessTruth:true, canonicalBackendOwner:"support", canonicalApiContracts:[contract("/api/v1/customer/support/cases","VIP session","KEYSET"),contract("/api/v1/customer/support/cases","VIP session","NONE",null,"POST")], compatibilityRoutes:[], cutoverPhase:"6.5", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-5-vip-support"], notes:"VIP identity derives from session." }),

    entry({ designChangePolicy:"PRESERVE", designChangeRationale:"Supplier shell, session lifecycle and application flow already serve the workflow; only wiring and state correctness change in this wave.", id:"supplier-auth-application", portal:"SUPPLIER", feature:"Supplier login, session and application", routesOrPages:["/supplier","supplier login","supplier application"], sourceFiles:["supplier-src/App.tsx","supplier-src/auth.tsx","shared/supplier/session.ts","shared/supplier/client.ts"], currentTruthSource:"canonical auth/supplier session; identity re-read from /auth/me", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"auth", canonicalApiContracts:[contract("/api/v1/auth/supplier/login","public","NONE",null,"POST"),contract("/api/v1/auth/me","session"),contract("/api/v1/auth/logout","session","NONE",null,"POST"),contract("/api/v1/suppliers/applications","public","NONE",null,"POST")], compatibilityRoutes:["POST /store/kolbe/supplier/auth/login","GET /store/kolbe/supplier/session","POST /store/kolbe/supplier/apply"], cutoverPhase:"6.2", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/phase-6-2-supplier-session.test.ts","test/phase-6-2-supplier-adapter.test.ts","test/auth-cutover.test.ts","test/session-security.test.ts"], decomposition:"Login body is never identity authority: after POST /auth/supplier/login the client re-reads GET /auth/me and rejects non-supplier or tenant-less sessions with 403. Demo mode is an explicit interface flag gated by NEXT_PUBLIC_SUPPLIER_DEMO, never a silent fallback.", notes:"Supplier ID, role and membership derive only from the server session. supplier-src/api.ts was removed." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-dashboard-analytics", portal:"SUPPLIER", feature:"Supplier dashboard and analytics", routesOrPages:["supplier dashboard","supplier analytics"], sourceFiles:["supplier-src/pages/dashboard.tsx","supplier-src/pages/analytics.tsx","shared/supplier/client.ts"], currentTruthSource:"supplier analytics service metrics", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"analytics", canonicalApiContracts:[contract("/api/v1/supplier/analytics/overview","supplier session"),contract("/api/v1/supplier/analytics/orders","supplier session"),contract("/api/v1/supplier/analytics/inventory","supplier session"),contract("/api/v1/supplier/analytics/settlement","supplier session")], compatibilityRoutes:[], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-states.test.ts","test/phase-6-2-supplier-render.test.tsx","test/supplier-empty-data.test.ts"], notes:"Static KPIs, the fabricated sales funnel and the hardcoded performance score were removed. A missing metric renders as an explicit dash and an analytics failure renders SERVER_ERROR, never zero." }),
    entry({ designChangePolicy:"RESTRUCTURE", designChangeRationale:"A staged commercial graph (attributes, variant matrix, ordered media, per-variant inventory, MOQ unit, SIZE_RUN package composition, pricing tiers) is a transactional editor, not a linear form. The eight-step wizard reached L4 capability but the operator cannot see accumulated state, validation is only surfaced at submit time, and variant/package/tier density fails narrow viewports. Step architecture, section-level validation summary and persistent review state are being restructured; the Kolbe identity and the eight domain sections are retained.", id:"supplier-products-intake", portal:"SUPPLIER", feature:"Products, intake and submissions", routesOrPages:["supplier products","supplier product editor"], sourceFiles:["supplier-src/pages/products.tsx","shared/supplier/client.ts"], currentTruthSource:"registered compat supplier product seam over the catalog module", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/compat/supplier/products","supplier session","OFFSET"),contract("/api/v1/catalog/compat/supplier-submissions","supplier session","NONE",null,"POST")], compatibilityRoutes:["GET/POST /store/kolbe/supplier/products"], cutoverPhase:"6.2", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", decomposition:"Fixture products were deleted; the registered compat seam is the only list contract that exists today. Submission prices travel as decimal strings and server-side validation messages are surfaced verbatim.", notes:"Supplier tenant is server-derived; no supplierId is sent from the browser." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-offers-rfqs", portal:"SUPPLIER", feature:"RFQs, offers and quotes", routesOrPages:["supplier RFQs","supplier quotes"], sourceFiles:["supplier-src/pages/rfqs.tsx","shared/supplier/client.ts"], currentTruthSource:"registered compat Offers seams", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"pricing", canonicalApiContracts:[contract("/api/v1/compat/supplier/rfqs","supplier session","OFFSET"),contract("/api/v1/offers/compat/rfqs/:id/quote","supplier session","NONE",null,"POST")], compatibilityRoutes:["GET /store/kolbe/supplier/rfqs","POST /store/kolbe/supplier/rfqs/:id/quote"], cutoverPhase:"6.2", preservationPolicy:"UPGRADE", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"Quote unit price is a decimal string; totals stay server-owned. A failed RFQ list renders an error state, never an empty inbox." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-orders-fulfillment", portal:"SUPPLIER", feature:"Orders, fulfillment and shipping", routesOrPages:["supplier orders","supplier order detail"], sourceFiles:["supplier-src/pages/orders.tsx","shared/supplier/client.ts","shared/supplier/present.ts"], currentTruthSource:"canonical supplier order state machine", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/supplier/orders","supplier session"),contract("/api/v1/supplier/orders/:id","supplier session"),contract("/api/v1/supplier/orders/:id/confirm","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/start-preparation","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/ready","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/dispatch","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/deliver","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/cancel","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/orders/:id/exceptions","supplier session"),contract("/api/v1/supplier/shipments/child/:childOrderId","supplier session")], compatibilityRoutes:["GET /store/kolbe/supplier/orders","POST /store/kolbe/supplier/orders/:id/status"], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", decomposition:"Browser authority over order status was removed: every transition goes to the canonical endpoint with an Idempotency-Key and expectedVersion, and the UI re-reads server state. Tracking codes are operator input only; Date.now generation is gone.", notes:"Cross-tenant access stays impossible: the server answers 403 SUPPLIER_OWNERSHIP_VIOLATION / 404 and the portal shows it." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-inventory-capacity", portal:"SUPPLIER", feature:"Inventory, capacity and holiday availability", routesOrPages:["supplier inventory","supplier capacity"], sourceFiles:["supplier-src/pages/inventory.tsx","supplier-src/pages/production.tsx","shared/supplier/client.ts"], currentTruthSource:"inventory module and production capacity periods", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"inventory", canonicalApiContracts:[contract("/api/v1/inventory/my","supplier session"),contract("/api/v1/supplier/analytics/inventory","supplier session"),contract("/api/v1/supplier/production/capacity-periods","supplier session","OFFSET"),contract("/api/v1/supplier/production/capacity-periods","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/capacity-periods/:id/closures","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/closures/:id/cancel","supplier session","NONE",null,"POST")], compatibilityRoutes:[], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], decomposition:"The kv_supplier_holidays localStorage record was deleted; closures are now server records. Availability stays a server computation and capacity is capability-gated.", notes:"Production capacity applies only to suppliers with a server-declared production capability." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-finance-settlement", portal:"SUPPLIER", feature:"Finance, settlement, withdrawals and proformas", routesOrPages:["supplier finance","supplier withdrawals"], sourceFiles:["supplier-src/pages/finance.tsx","shared/supplier/client.ts"], currentTruthSource:"supplier financial account and finance modules", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"settlement", canonicalApiContracts:[contract("/api/v1/supplier/financial-account/summary","supplier session"),contract("/api/v1/supplier/financial-account/history","supplier session","OFFSET"),contract("/api/v1/supplier/financial-account/withdrawals","supplier session","OFFSET"),contract("/api/v1/supplier/financial-account/withdrawals","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/financial-account/withdrawals/:id","supplier session"),contract("/api/v1/supplier/finance/proformas","supplier session","OFFSET"),contract("/api/v1/supplier/compliance/:supplierId/settlement-eligibility","supplier session")], compatibilityRoutes:[], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"The hardcoded ledger, deduction table and balance grid were removed. Balances and withdrawable amounts are server-owned decimal strings; withdrawal requests carry an Idempotency-Key." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-team", portal:"SUPPLIER", feature:"Supplier team, roles and permissions", routesOrPages:["supplier team"], sourceFiles:["supplier-src/pages/team.tsx","shared/supplier/session.ts"], currentTruthSource:"server session role plus server-declared supplier capabilities", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"supplier-team", canonicalApiContracts:[contract("/api/v1/auth/me","session"),contract("/api/v1/supplier/production/capabilities","supplier session")], compatibilityRoutes:[], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-session.test.ts","test/phase-6-2-supplier-render.test.tsx"], decomposition:"The localStorage role generator was deleted; the page now shows only server-sourced role and capability data. Member CRUD has no supplier-facing backend contract yet (modules/supplier-team ships a Module with no controller and GET /suppliers/:id/members is admin-only), so the page states that gap instead of inventing routes.", notes:"Permissions and membership come from the server, never browser-generated role IDs. Backend gap recorded in the Phase 6.2 report." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-support-compliance", portal:"SUPPLIER", feature:"Support, compliance and quality documents", routesOrPages:["supplier support","supplier compliance","supplier documents"], sourceFiles:["supplier-src/pages/support.tsx","supplier-src/pages/compliance.tsx","shared/supplier/client.ts"], currentTruthSource:"compliance and support modules", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"compliance", canonicalApiContracts:[contract("/api/v1/supplier/compliance/:supplierId/profile","supplier session"),contract("/api/v1/supplier/compliance/:supplierId/documents","supplier session"),contract("/api/v1/supplier/compliance/:supplierId/documents","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/compliance/documents/:documentId/access","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/compliance/:supplierId/holds","supplier session"),contract("/api/v1/supplier/compliance/:supplierId/bank","supplier session"),contract("/api/v1/supplier/compliance/:supplierId/agreement","supplier session"),contract("/api/v1/supplier/support/cases","supplier session","OFFSET"),contract("/api/v1/supplier/support/cases","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/support/cases/:id","supplier session"),contract("/api/v1/supplier/support/cases/:id/messages","supplier session","NONE",null,"POST")], compatibilityRoutes:["GET/POST /store/kolbe/supplier/tickets"], cutoverPhase:"6.2", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-states.test.ts"], decomposition:"Compliance owns profile/documents/agreement/holds/bank/eligibility; Support owns cases and messages. The UI groups them in navigation but the adapters stay separate. Documents are opened only through the server-issued access grant, never a raw object key.", notes:"Private object keys never enter portal responses or URLs." }),
    entry({ designChangePolicy:"PRESERVE", id:"supplier-production-qc", portal:"SUPPLIER", feature:"Production, samples, change requests, QC, lots and recall", routesOrPages:["supplier production","supplier production job"], sourceFiles:["supplier-src/pages/production.tsx","shared/supplier/client.ts"], currentTruthSource:"production module workflows", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"production", canonicalApiContracts:[contract("/api/v1/supplier/production/jobs","supplier session","OFFSET"),contract("/api/v1/supplier/production/jobs/:id","supplier session"),contract("/api/v1/supplier/production/jobs/:id/start","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:id/block","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:id/complete","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:id/cancel","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:id/actual-units","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:jobId/milestones/:milestoneId/complete","supplier session","NONE",null,"POST"),contract("/api/v1/supplier/production/jobs/:jobId/samples","supplier session"),contract("/api/v1/supplier/production/jobs/:jobId/events","supplier session","OFFSET"),contract("/api/v1/supplier/production/capabilities","supplier session"),contract("/api/v1/supplier/production/recalls","supplier session","OFFSET")], compatibilityRoutes:[], cutoverPhase:"6.2", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-2-supplier-adapter.test.ts","test/phase-6-2-supplier-session.test.ts","test/phase-6-2-supplier-states.test.ts"], decomposition:"Hardcoded workflow fixtures and browser-local mutation were removed; every transition sends an Idempotency-Key and re-reads server state. The whole domain is capability-gated through shared/permissions canUseProduction.", notes:"Supplier and Manufacturer are not synonyms: without a server-declared production capability the section is inaccessible." }),

  entry({ designChangePolicy:"PRESERVE", id:"admin-shell-permissions", portal:"ADMIN", feature:"Admin shell, navigation and permission visibility", routesOrPages:["/admin","Admin","AdminPortal"], sourceFiles:["storefront/pages/Admin.tsx","storefront/pages/AdminPortal.tsx"], currentTruthSource:"admin session with partial browser assumptions", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"admin", canonicalApiContracts:[contract("/api/v1/auth/me","admin session")], compatibilityRoutes:["POST /store/kolbe/admin/login","GET /store/kolbe/admin/session"], cutoverPhase:"6.1", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/auth-cutover.test.ts","test/phase-6-1-permissions.test.ts","planned:phase-6-4-admin-shell-wiring"], decomposition:"Server session supplies role and granular permissions; browser only renders allowed controls.", notes:"Phase 6.1 provides the permission/capability primitive; Admin does not imply unrestricted browser authority." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-control-tower", portal:"ADMIN", feature:"Control tower and operational KPI overview", routesOrPages:["Admin operations dashboard"], sourceFiles:["storefront/pages/AdminOperations.tsx","storefront/pages/AdminPortal.tsx"], currentTruthSource:"hardcoded KPI and operational datasets", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"analytics", canonicalApiContracts:[contract("/api/v1/admin/analytics/operations","admin session","NONE","analytics:view")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-control-tower"], notes:"Fake KPI values become truthful empty/error states." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-supplier-approval", portal:"ADMIN", feature:"Supplier applications and approvals", routesOrPages:["Admin supplier management"], sourceFiles:["storefront/pages/AdminPortal.tsx","storefront/lib/wholesaleApi.ts"], currentTruthSource:"canonical Suppliers through compatibility API", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"suppliers", canonicalApiContracts:[contract("/api/v1/compat/admin/supplier-applications","admin session","OFFSET","supplier:application:view"),contract("/api/v1/suppliers/applications/:id/decision","admin session","NONE","supplier:application:manage","POST")], compatibilityRoutes:["GET /store/kolbe/admin/supplier-applications","PATCH /store/kolbe/admin/supplier-applications/:id"], cutoverPhase:"6.4", preservationPolicy:"UPGRADE", parityTests:["test/phase-5-12-c-writer-cutover.test.ts","planned:phase-6-4-supplier-approval"], notes:"Approval keeps the existing transactional owner orchestration." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-catalog-retail-products", portal:"ADMIN", feature:"Retail products, media, taxonomy and moderation", routesOrPages:["AdminProductEditor","ProductMediaStudio","CatalogTaxonomyManager"], sourceFiles:["storefront/pages/AdminProductEditor.tsx","storefront/pages/ProductMediaStudio.tsx","storefront/pages/CatalogTaxonomyManager.tsx","storefront/adminProducts.ts"], currentTruthSource:"localStorage products/trash plus canonical supplier catalog compatibility reads", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/admin/catalog/products","admin session","CURSOR","catalog:view"),contract("/api/v1/admin/catalog/products/:id","admin session","NONE","catalog:manage","PATCH")], compatibilityRoutes:["GET /store/kolbe/admin/catalog","POST /store/kolbe/admin/catalog/:id/status"], cutoverPhase:"6.4", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-4-admin-catalog"], decomposition:"Catalog API owns products/moderation; local draft/trash UI becomes server-versioned workflow without feature loss.", notes:"No product or price remains localStorage authority." }),
  entry({ designChangePolicy:"EXTEND", designChangeRationale:"The canonical moderation page already reads the real submission graph and exposes the three real backend actions, so its structure is sound. It is being extended, not rebuilt: explicit state coverage, conflict-after-stale-state handling and double-click replay protection on the destructive approve/reject actions.", id:"admin-supplier-product-moderation", portal:"ADMIN", feature:"Canonical supplier product submission review and approval", routesOrPages:["SupplierModeration","WholesaleAdmin catalog tab"], sourceFiles:["storefront/pages/SupplierModeration.tsx","shared/supplier/client.ts"], currentTruthSource:"canonical supplier_product_submission through the shared supplier boundary", classification:"CANONICAL_API", businessTruth:true, canonicalBackendOwner:"catalog", canonicalApiContracts:[contract("/api/v1/catalog/supplier-submissions","admin session","NONE","retail:catalog:manage"),contract("/api/v1/catalog/supplier-submissions/:id","admin session","NONE","retail:catalog:manage"),contract("/api/v1/catalog/supplier-submissions/:id/approve-new","admin session","NONE","retail:catalog:manage","POST"),contract("/api/v1/catalog/supplier-submissions/:id/approve-existing","admin session","NONE","retail:catalog:manage","POST"),contract("/api/v1/catalog/supplier-submissions/:id/reject","admin session","NONE","retail:catalog:manage","POST")], compatibilityRoutes:[], cutoverPhase:"6.7", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["test/phase-6-7-admin-moderation.test.tsx","test/phase-6-7-product-editor.test.tsx","test/phase-6-7-product-graph-core.test.ts"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", decomposition:"Replaces the WholesaleAdmin catalog tab, which invented draft/submitted/approved/changes_requested/rejected statuses in the browser and mutated them through a select with no server destination. Statuses now come only from supplier_product_submission; approve-as-existing requires an explicit canonical product chosen through GET /api/v1/catalog/products?q= and never fuzzy-matches in the browser.", notes:"Only the three actions the backend really has are exposed. There is no separate request-changes action server-side, so the reject note is presented honestly as the correction feedback. Every action re-reads list and detail from the server; local status is never mutated optimistically." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-retail-operations", portal:"ADMIN", feature:"Retail orders, fulfillment, shipping, returns and refunds", routesOrPages:["Admin retail operations"], sourceFiles:["storefront/pages/AdminOperations.tsx"], currentTruthSource:"hardcoded/local operational tables", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/admin/retail/orders","admin session","KEYSET","retail:orders:view"),contract("/api/v1/admin/retail/orders/:id/actions","admin session","NONE","retail:orders:manage","POST")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-retail-operations"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"UI status actions map to owner state machines." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-wholesale-operations", portal:"ADMIN", feature:"Wholesale orders, RFQs, purchase orders and catalog", routesOrPages:["WholesaleAdmin","WholesaleCatalogManager"], sourceFiles:["storefront/pages/WholesaleAdmin.tsx","storefront/pages/WholesaleCatalogManager.tsx","storefront/lib/wholesaleApi.ts"], currentTruthSource:"compatibility API mixed with localStorage wholesale catalog and deprecated buttons", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"orders", canonicalApiContracts:[contract("/api/v1/compat/admin/orders","admin session","KEYSET","wholesale:orders:view"),contract("/api/v1/admin/wholesale/orders/:id/cancel","admin session","NONE","wholesale:orders:manage","POST")], compatibilityRoutes:["GET /store/kolbe/admin/orders","GET /store/kolbe/admin/purchase-orders","GET/POST /store/kolbe/admin/rfqs","POST /store/kolbe/admin/orders/:id/cancel"], cutoverPhase:"6.4", preservationPolicy:"MERGE_NO_LOSS", parityTests:["test/phase-5-12-b-read-cutover.test.ts","planned:phase-6-4-wholesale-operations"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", channelOwnership:"WHOLESALE_KOLBE_AND_SUPPLIERS", decomposition:"Live orders/RFQs use owner APIs; local catalog data is replaced; deprecated approve/status routes remain disabled and are never future authority.", notes:"Deprecated routes are removal candidates only after parity." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-vip-management", portal:"ADMIN", feature:"VIP accounts, plans and access", routesOrPages:["Admin VIP management"], sourceFiles:["storefront/pages/AdminPortal.tsx","storefront/lib/wholesaleApi.ts"], currentTruthSource:"canonical accounts via compatibility API mixed with kv_vip_plans_v1", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"vip", canonicalApiContracts:[contract("/api/v1/compat/admin/accounts","admin session","OFFSET","vip:account:view"),contract("/api/v1/vip/compat/accounts/:id/status","admin session","NONE","vip:account:manage","POST")], compatibilityRoutes:["GET /store/kolbe/admin/accounts","POST /store/kolbe/admin/accounts/:id/status"], cutoverPhase:"6.4", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-4-vip-admin"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", decomposition:"VIP accounts remain canonical; local plan commercial fields move to VIP/Pricing contracts.", notes:"Annual price and minimum order are backend commercial truth." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-crm", portal:"ADMIN", feature:"CRM customers, segments, notes and lifecycle", routesOrPages:["AdminCRM"], sourceFiles:["storefront/pages/AdminCRM.tsx"], currentTruthSource:"localStorage/hardcoded CRM datasets", classification:"LOCAL_STORAGE", businessTruth:true, canonicalBackendOwner:"crm", canonicalApiContracts:[contract("/api/v1/admin/crm/customers","admin session","KEYSET","crm:view"),contract("/api/v1/admin/crm/customers/:id/notes","admin session","NONE","crm:manage","POST")], compatibilityRoutes:[], cutoverPhase:"6.5", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-5-crm"], notes:"Customer focus cache may remain presentation-only after server lookup." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-support", portal:"ADMIN", feature:"Support center, cases and replies", routesOrPages:["AdminSupportCenter"], sourceFiles:["storefront/pages/AdminSupportCenter.tsx","storefront/lib/wholesaleApi.ts"], currentTruthSource:"canonical Support compatibility API plus hardcoded panels", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"support", canonicalApiContracts:[contract("/api/v1/compat/admin/tickets","admin session","KEYSET","support:case:view"),contract("/api/v1/admin/support/compat/tickets/:id","admin session","NONE","support:case:manage","POST")], compatibilityRoutes:["GET /store/kolbe/admin/tickets","POST /store/kolbe/admin/tickets/:id"], cutoverPhase:"6.5", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-5-admin-support"], decomposition:"Cases/replies use Support API; local canned presentation does not own case truth.", notes:"Attachment object keys remain private." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-notifications", portal:"ADMIN", feature:"Messaging automation, templates, outbox and provider settings", routesOrPages:["MessagingAutomationCenter"], sourceFiles:["storefront/pages/MessagingAutomationCenter.tsx"], currentTruthSource:"localStorage templates/outbox/provider secret", classification:"LOCAL_STORAGE", businessTruth:true, canonicalBackendOwner:"notifications", canonicalApiContracts:[contract("/api/v1/admin/notifications/templates","admin session","OFFSET","notifications:manage"),contract("/api/v1/admin/notifications/outbox","admin session","KEYSET","notifications:view")], compatibilityRoutes:[], cutoverPhase:"6.5", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-5-notifications"], uiStates:[...standardStates,"PROVIDER_UNAVAILABLE"], notes:"Provider secrets must never remain browser storage; real provider remains unavailable until configured server-side." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-cms-builder", portal:"CMS_EDITOR", feature:"Site builder, hero and design centers", routesOrPages:["SiteBuilder","HeroStudio","SiteDesignCenter","DesignSystemStudio"], sourceFiles:["storefront/pages/SiteBuilder.tsx","storefront/pages/HeroStudio.tsx","storefront/pages/SiteDesignCenter.tsx","storefront/pages/DesignSystemStudio.tsx","storefront/siteSettings.ts","storefront/designSystem.ts"], currentTruthSource:"CMS compatibility save plus kolbe-site-content-v3 editor cache and presentation defaults", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"cms", canonicalApiContracts:[contract("/api/v1/cms/compat/site-settings","admin session","NONE","cms:publish","PUT")], compatibilityRoutes:["PUT /store/kolbe/admin/site-settings","GET /store/kolbe/site/settings"], cutoverPhase:"6.4", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-4-cms-builder"], decomposition:"CMS owns published content; browser storage is editor cache; design defaults are presentation fallback; Catalog/Promotions stay separate owners.", notes:"No visual redesign; existing builder UI and component slots remain." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-campaign-center", portal:"ADMIN", feature:"Campaign planning and promotion operations", routesOrPages:["CampaignCenter"], sourceFiles:["storefront/pages/CampaignCenter.tsx"], currentTruthSource:"hardcoded campaign dataset and browser mutation", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"promotions", canonicalApiContracts:[contract("/api/v1/admin/promotions","admin session","CURSOR","promotions:view"),contract("/api/v1/admin/promotions","admin session","NONE","promotions:manage","POST")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-promotions"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"CampaignCenter remains UI, while Promotions owns eligibility and discount truth." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-analytics", portal:"ADMIN", feature:"Analytics and exports", routesOrPages:["Admin analytics panels"], sourceFiles:["storefront/pages/AdminOperations.tsx","storefront/lib/analytics.ts"], currentTruthSource:"mixed client analytics and hardcoded panels", classification:"MIXED", businessTruth:true, canonicalBackendOwner:"analytics", canonicalApiContracts:[contract("/api/v1/admin/analytics/reports","admin session","OFFSET","analytics:view"),contract("/api/v1/admin/analytics/exports","admin session","NONE","analytics:export","POST")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"MERGE_NO_LOSS", parityTests:["planned:phase-6-4-analytics"], decomposition:"Client events remain telemetry inputs; reports/exports are canonical scoped outputs.", notes:"Export expiry and CSV safety remain server-owned." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-finance-settlement", portal:"ADMIN", feature:"Finance, settlement, withdrawal, payout and invoicing", routesOrPages:["Admin finance operations"], sourceFiles:["storefront/pages/AdminOperations.tsx"], currentTruthSource:"hardcoded/local operational values", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"finance", canonicalApiContracts:[contract("/api/v1/admin/finance/ledger","admin session","KEYSET","finance:view"),contract("/api/v1/admin/settlements","admin session","KEYSET","settlement:view")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-finance-settlement"], moneySemantics:"DECIMAL_STRING_FROM_API_FORMAT_ONLY_NO_FLOAT_AUTHORITY", notes:"Order, payment, ledger, settlement and payout remain distinct aggregates." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-production-qc", portal:"ADMIN", feature:"Production and QC administration", routesOrPages:["Admin production/QC"], sourceFiles:["storefront/pages/AdminOperations.tsx"], currentTruthSource:"hardcoded workflow panels", classification:"HARDCODED_RUNTIME", businessTruth:true, canonicalBackendOwner:"production", canonicalApiContracts:[contract("/api/v1/admin/production/jobs","admin session","KEYSET","production:view")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-production-qc"], notes:"Capability constraints remain explicit." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-audit-logs", portal:"ADMIN", feature:"Audit and operational logs", routesOrPages:["AdminLogs"], sourceFiles:["storefront/pages/AdminLogs.tsx","storefront/lib/wholesaleApi.ts"], currentTruthSource:"canonical Audit/telemetry via compatibility API", classification:"COMPAT_PROXY", businessTruth:true, canonicalBackendOwner:"audit", canonicalApiContracts:[contract("/api/v1/compat/admin/audit-logs","admin session","KEYSET","audit:view"),contract("/api/v1/compat/admin/logs","admin session","OFFSET","logs:view")], compatibilityRoutes:["GET /store/kolbe/admin/audit-logs","GET/PATCH /store/kolbe/admin/logs[/:id]"], cutoverPhase:"6.4", preservationPolicy:"UPGRADE", parityTests:["test/log-ingestion-guard.test.ts","planned:phase-6-4-admin-logs"], notes:"Sensitive payloads remain sink-redacted." }),
  entry({ designChangePolicy:"PRESERVE", id:"admin-settings", portal:"ADMIN", feature:"Operational settings, warehouses, approval and retention UI", routesOrPages:["Admin settings panels"], sourceFiles:["storefront/pages/AdminOperations.tsx"], currentTruthSource:"localStorage kv_admin_system and warehouse records", classification:"LOCAL_STORAGE", businessTruth:true, canonicalBackendOwner:"admin", canonicalApiContracts:[contract("/api/v1/admin/settings","admin session","NONE","settings:view"),contract("/api/v1/admin/settings","admin session","NONE","settings:manage","PATCH")], compatibilityRoutes:[], cutoverPhase:"6.4", preservationPolicy:"REPLACE_WITH_CORRECT_IMPLEMENTATION", parityTests:["planned:phase-6-4-admin-settings"], notes:"Security/provider secrets are server configuration, never browser settings." }),

  entry({ designChangePolicy:"EXTEND", designChangeRationale:"The semantic token architecture (Heritage light/dark roles, Persian-first Vazirmatn typography) is retained as the single source of style truth. It is being extended with governed tokens for density, motion and reduced-motion, and with the numeric/LTR isolation role, so that screens stop inventing one-off colours, radii and durations.", id:"shared-theme", portal:"SHARED", feature:"Theme and responsive presentation preference", routesOrPages:["all storefront routes"], sourceFiles:["storefront/theme.ts","storefront/App.tsx"], currentTruthSource:"localStorage presentation preference", classification:"PRESENTATION_DEFAULT", businessTruth:false, canonicalBackendOwner:"cms", canonicalApiContracts:[contract("/api/v1/cms/public/site-settings","public")], compatibilityRoutes:[], cutoverPhase:"6.7", preservationPolicy:"KEEP", parityTests:["planned:phase-6-7-visual-freeze"], identityAuthority:"NOT_APPLICABLE", notes:"Theme preference is not business truth." }),
  entry({ designChangePolicy:"PRESERVE", id:"shared-commerce-events", portal:"SHARED", feature:"Client analytics and commerce event buffer", routesOrPages:["all commerce journeys"], sourceFiles:["storefront/lib/analytics.ts","storefront/lib/clientLogger.ts"], currentTruthSource:"bounded local event buffer and telemetry endpoint", classification:"BROWSER_EPHEMERAL", businessTruth:false, canonicalBackendOwner:"operational-telemetry", canonicalApiContracts:[contract("/api/v1/telemetry/client-events","public","NONE",null,"POST")], compatibilityRoutes:["POST /store/kolbe/logs/client"], cutoverPhase:"6.7", preservationPolicy:"KEEP", parityTests:["test/log-ingestion-guard.test.ts"], identityAuthority:"NOT_APPLICABLE", notes:"Telemetry never becomes commerce authority." }),
];

export const COMPATIBILITY_ROUTE_SUMMARY = { total: 47, NEXT_PROXY_TO_NEST: 42, LEGACY_READ: 0, LEGACY_WRITE: 0, MISSING_CANONICAL_SEAM: 0, DEPRECATED: 2, STATIC_MOCK: 3 } as const;
