import { useState } from "react";
import { loadCatalogTaxonomy, saveCatalogTaxonomy, type CatalogTaxonomy, type TaxonomyOption } from "../lib/catalogTaxonomy";

const labels: Record<keyof CatalogTaxonomy, [string, string]> = { categories: ["دسته‌بندی", "مثل کت، کفش یا اکسسوری"], styles: ["استایل", "مثل کلاسیک یا مینیمال"], seasons: ["فصل", "فصل یا بازه عرضه"], collections: ["کالکشن", "مجموعه‌های قابل انتخاب محصول"] };
const field = "h-10 w-full border border-neutral-300 px-3 text-[10.5px] outline-none focus-visible:ring-2 focus-visible:ring-[#011c3a]";

export default function CatalogTaxonomyManager({ onClose }: { onClose: () => void }) {
  const [value, setValue] = useState<CatalogTaxonomy>(loadCatalogTaxonomy);
  const [drafts, setDrafts] = useState<Record<keyof CatalogTaxonomy, string>>({ categories: "", styles: "", seasons: "", collections: "" });
  const [saved, setSaved] = useState(false);
  const add = (key: keyof CatalogTaxonomy) => { const label = drafts[key].trim(); if (!label) return; const item: TaxonomyOption = { id: `${key.slice(0, 3)}-${Date.now()}`, label }; setValue((current) => ({ ...current, [key]: [...current[key], item] })); setDrafts((current) => ({ ...current, [key]: "" })); };
  const remove = (key: keyof CatalogTaxonomy, id: string) => setValue((current) => ({ ...current, [key]: current[key].filter((item) => item.id !== id) }));
  const save = () => { saveCatalogTaxonomy(value); setSaved(true); setTimeout(() => setSaved(false), 1400); };
  return <section className="mb-5 border border-neutral-200 bg-white p-4 lg:p-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] tracking-[.2em] text-neutral-400">CATALOG DEFINITIONS</p><h2 className="mt-2 text-[15px] font-medium">تعریف دسته، استایل، فصل و کالکشن</h2><p className="mt-1 text-[9.5px] text-neutral-500">تعریف‌های ذخیره‌شده مستقیماً در فرم ایجاد و ویرایش محصول قابل انتخاب‌اند.</p></div><div className="flex gap-2"><button onClick={onClose} className="h-9 border border-neutral-300 px-3 text-[10px]">بستن</button><button onClick={save} className="h-9 bg-[#011c3a] px-4 text-[10px] text-white">ذخیره تعریف‌ها</button></div></header>{saved ? <p role="status" className="mt-3 border border-emerald-200 bg-emerald-50 px-3 py-2 text-[9.5px] text-emerald-700">تعریف‌ها ذخیره و فرم محصول به‌روز شد.</p> : null}<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{(Object.keys(labels) as (keyof CatalogTaxonomy)[]).map((key) => <article key={key} className="border border-neutral-200 p-3"><h3 className="text-[11px] font-medium">{labels[key][0]}</h3><p className="mt-1 text-[8.5px] text-neutral-400">{labels[key][1]}</p><div className="mt-3 flex gap-1.5"><input aria-label={`تعریف ${labels[key][0]}`} value={drafts[key]} onChange={(event) => setDrafts((current) => ({ ...current, [key]: event.target.value }))} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(key); } }} className={field} /><button onClick={() => add(key)} className="h-10 shrink-0 border border-[#011c3a] px-3 text-[10px]">+</button></div><div className="mt-3 max-h-44 space-y-1 overflow-y-auto">{value[key].map((item) => <div key={item.id} className="flex items-center justify-between gap-2 bg-neutral-50 px-2 py-2 text-[9.5px]"><span className="truncate">{item.label}</span><button aria-label={`حذف ${item.label}`} onClick={() => remove(key, item.id)} className="shrink-0 text-red-700">×</button></div>)}</div></article>)}</div></section>;
}
