import { useMemo, useState } from "react";
import { fileToOptimizedDataUrl } from "../lib/imageUpload";
import { fa, toman } from "../utils/format";

export type KolbeWholesaleProduct = { id:string; name:string; sku:string; category:string; price:number; retailPrice:number; minOrder:number; stock:number; leadTime:number; image:string; status:"active"|"draft" };
export const KOLBE_WHOLESALE_CATALOG_KEY="kv_kolbe_wholesale_catalog_v1";
const seed:KolbeWholesaleProduct[]=[
  {id:"kw-1",name:"بلیزر آکسفورد — پک عمده",sku:"KV-BLZ-01-W",category:"کت و بلیزر",price:3_150_000,retailPrice:4_850_000,minOrder:6,stock:42,leadTime:1,image:"/images/model-front.jpg",status:"active"},
  {id:"kw-2",name:"پیراهن آکسفورد — پک رنگی",sku:"KV-SH-08-W",category:"پیراهن",price:1_480_000,retailPrice:2_390_000,minOrder:8,stock:28,leadTime:2,image:"/images/shirt-front.jpg",status:"active"},
];
export function loadKolbeWholesaleCatalog(){try{const raw=localStorage.getItem(KOLBE_WHOLESALE_CATALOG_KEY);return raw?JSON.parse(raw) as KolbeWholesaleProduct[]:seed}catch{return seed}}
const field="h-10 w-full border border-neutral-300 bg-white px-3 text-[10.5px] outline-none focus-visible:ring-2 focus-visible:ring-[#011c3a]";
const empty:Omit<KolbeWholesaleProduct,"id">={name:"",sku:"",category:"",price:0,retailPrice:0,minOrder:6,stock:0,leadTime:1,image:"",status:"draft"};

export default function WholesaleCatalogManager(){
  const [items,setItems]=useState(loadKolbeWholesaleCatalog);
  const [form,setForm]=useState(empty);
  const [open,setOpen]=useState(false);
  const [query,setQuery]=useState("");
  const [notice,setNotice]=useState("");
  const visible=useMemo(()=>items.filter(item=>(item.name+item.sku+item.category).toLowerCase().includes(query.trim().toLowerCase())),[items,query]);
  const save=(next:KolbeWholesaleProduct[])=>{setItems(next);localStorage.setItem(KOLBE_WHOLESALE_CATALOG_KEY,JSON.stringify(next));setNotice("کاتالوگ عمده کلبه ذخیره شد.");setTimeout(()=>setNotice(""),1500)};
  const submit=()=>{if(!form.name.trim()||!form.sku.trim()||form.price<=0||form.minOrder<1){setNotice("نام، SKU، قیمت و حداقل سفارش را کامل کنید.");return}save([{...form,id:`kw-${Date.now()}`},...items]);setForm(empty);setOpen(false)};
  return <section>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] tracking-[.2em] text-neutral-400">KOLBE OWN CATALOG</p><h2 className="mt-1 text-[17px] font-medium">محصولات عمده خود کلبه</h2><p className="mt-1 text-[10px] leading-5 text-neutral-500">آپلود محصول عمده از بخش خرده‌فروشی جداست؛ قیمت همکاری، MOQ، موجودی و زمان تامین اینجا کنترل می‌شود.</p></div><button onClick={()=>setOpen(value=>!value)} className="h-10 bg-[#011c3a] px-4 text-[10px] text-white">{open?"بستن فرم":"+ محصول عمده کلبه"}</button></header>
    {notice&&<p role="status" className={(notice.startsWith("نام")?"border-red-200 bg-red-50 text-red-700":"border-[#b9cfbc] bg-[#edf3ee] text-[#36563a]")+" mt-4 border px-3 py-2 text-[10px]"}>{notice}</p>}
    {open&&<div className="mt-4 grid gap-5 border border-neutral-200 bg-white p-5 xl:grid-cols-[1fr_260px]"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[9.5px]">نام محصول<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={field+" mt-1"}/></label><label className="text-[9.5px]">SKU<input dir="ltr" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} className={field+" mt-1"}/></label><label className="text-[9.5px]">دسته‌بندی<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={field+" mt-1"}/></label><label className="text-[9.5px]">قیمت مصرف‌کننده<input type="number" value={form.retailPrice} onChange={e=>setForm({...form,retailPrice:Number(e.target.value)})} className={field+" mt-1"}/></label><label className="text-[9.5px]">قیمت عمده<input type="number" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})} className={field+" mt-1"}/></label><label className="text-[9.5px]">حداقل سفارش<input type="number" min="1" value={form.minOrder} onChange={e=>setForm({...form,minOrder:Number(e.target.value)})} className={field+" mt-1"}/></label><label className="text-[9.5px]">موجودی آماده<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})} className={field+" mt-1"}/></label><label className="text-[9.5px]">زمان تامین (روز)<input type="number" min="0" value={form.leadTime} onChange={e=>setForm({...form,leadTime:Number(e.target.value)})} className={field+" mt-1"}/></label><label className="text-[9.5px] sm:col-span-2">لینک تصویر / CDN<input dir="ltr" value={form.image} onChange={e=>setForm({...form,image:e.target.value})} className={field+" mt-1"}/></label><button onClick={submit} className="h-10 bg-[#011c3a] px-4 text-[10px] text-white sm:col-span-2">ذخیره محصول عمده</button></div><label className="flex min-h-64 cursor-pointer flex-col items-center justify-center border border-dashed bg-neutral-50 p-4 text-center"><input type="file" accept="image/*" className="sr-only" onChange={async e=>{const file=e.target.files?.[0];if(file)setForm({...form,image:await fileToOptimizedDataUrl(file,1200,.84)})}}/>{form.image?<img src={form.image} alt="پیش‌نمایش محصول عمده" className="aspect-[4/5] w-full object-cover"/>:<><b className="text-[11px]">آپلود تصویر</b><span className="mt-2 text-[9px] text-neutral-400">یا لینک CDN را وارد کنید</span></>}</label></div>}
    <div className="mt-5 flex items-center justify-between border border-neutral-200 bg-white p-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام، SKU یا دسته" className={field+" max-w-md"}/><span className="text-[9px] text-neutral-400">{fa(visible.length)} محصول</span></div>
    <div className="mt-3 overflow-x-auto border border-neutral-200 bg-white"><table className="w-full min-w-[820px] text-right text-[10px]"><thead className="bg-neutral-50"><tr>{["محصول","SKU","قیمت عمده","حاشیه همکاری","MOQ","موجودی","تامین","وضعیت",""].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody>{visible.map(item=><tr key={item.id} className="border-t hover:bg-neutral-50"><td className="p-3"><span className="flex items-center gap-3"><img src={item.image||"/images/flat.jpg"} alt={item.name} className="h-12 w-10 object-cover"/><b className="font-medium">{item.name}</b></span></td><td className="p-3" dir="ltr">{item.sku}</td><td className="p-3">{toman(item.price)}</td><td className="p-3">{item.retailPrice?fa(Math.round((1-item.price/item.retailPrice)*100)):fa(0)}٪</td><td className="p-3">{fa(item.minOrder)}</td><td className="p-3">{fa(item.stock)}</td><td className="p-3">{item.leadTime?`${fa(item.leadTime)} روز`:"آماده"}</td><td className="p-3"><button onClick={()=>save(items.map(x=>x.id===item.id?{...x,status:x.status==="active"?"draft":"active"}:x))} className={item.status==="active"?"text-emerald-700 underline":"text-neutral-500 underline"}>{item.status==="active"?"فعال":"پیش‌نویس"}</button></td><td className="p-3"><button onClick={()=>save(items.filter(x=>x.id!==item.id))} className="text-red-700 underline">حذف</button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-10 text-center text-[10px] text-neutral-400">محصول عمده‌ای پیدا نشد.</p>}</div>
  </section>
}
