// augmentation-refs.d.ts
// Auto-generated by Medusa — do not edit manually.
// Re-generated on `medusa build` and `medusa develop`.
/// <reference types="@medusajs/medusa/stock-location" />
/// <reference types="@medusajs/medusa/inventory" />
/// <reference types="@medusajs/medusa/product" />
/// <reference types="@medusajs/medusa/pricing" />
/// <reference types="@medusajs/medusa/promotion" />
/// <reference types="@medusajs/medusa/customer" />
/// <reference types="@medusajs/medusa/sales-channel" />
/// <reference types="@medusajs/medusa/cart" />
/// <reference types="@medusajs/medusa/region" />
/// <reference types="@medusajs/medusa/api-key" />
/// <reference types="@medusajs/medusa/store" />
/// <reference types="@medusajs/medusa/tax" />
/// <reference types="@medusajs/medusa/currency" />
/// <reference types="@medusajs/medusa/payment" />
/// <reference types="@medusajs/medusa/order" />
/// <reference types="@medusajs/medusa/settings" />
/// <reference types="@medusajs/medusa/auth" />
/// <reference types="@medusajs/medusa/user" />
/// <reference types="@medusajs/medusa/fulfillment" />
/// <reference types="@medusajs/medusa/notification" />
/// <reference types="@medusajs/medusa/cache-inmemory" />
/// <reference types="@medusajs/medusa/event-bus-local" />
/// <reference types="@medusajs/medusa/workflow-engine-inmemory" />
/// <reference types="@medusajs/medusa/locking" />
/// <reference types="@medusajs/medusa/file" />
